
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Facility: 'Facility',
  FacilityReportType: 'FacilityReportType',
  Indicator: 'Indicator',
  LineList: 'LineList',
  IndicatorType: 'IndicatorType',
  StagedIndicator: 'StagedIndicator',
  ReportQueue: 'ReportQueue'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const FacilityScalarFieldEnum = {
  id: 'id',
  name: 'name',
  location: 'location',
  data: 'data',
  createdAt: 'createdAt',
  synced: 'synced',
  syncedAt: 'syncedAt'
} as const

export type FacilityScalarFieldEnum = (typeof FacilityScalarFieldEnum)[keyof typeof FacilityScalarFieldEnum]


export const FacilityReportTypeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  kenyaEmrReportUuid: 'kenyaEmrReportUuid',
  reportType: 'reportType',
  isReporting: 'isReporting',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type FacilityReportTypeScalarFieldEnum = (typeof FacilityReportTypeScalarFieldEnum)[keyof typeof FacilityReportTypeScalarFieldEnum]


export const IndicatorScalarFieldEnum = {
  id: 'id',
  facilityId: 'facilityId',
  indicatorId: 'indicatorId',
  name: 'name',
  value: 'value',
  period: 'period',
  data: 'data',
  createdAt: 'createdAt',
  synced: 'synced',
  syncedAt: 'syncedAt'
} as const

export type IndicatorScalarFieldEnum = (typeof IndicatorScalarFieldEnum)[keyof typeof IndicatorScalarFieldEnum]


export const LineListScalarFieldEnum = {
  id: 'id',
  facilityId: 'facilityId',
  patientId: 'patientId',
  data: 'data',
  createdAt: 'createdAt',
  synced: 'synced',
  syncedAt: 'syncedAt'
} as const

export type LineListScalarFieldEnum = (typeof LineListScalarFieldEnum)[keyof typeof LineListScalarFieldEnum]


export const IndicatorTypeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  query: 'query',
  source: 'source',
  apiUrl: 'apiUrl',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type IndicatorTypeScalarFieldEnum = (typeof IndicatorTypeScalarFieldEnum)[keyof typeof IndicatorTypeScalarFieldEnum]


export const StagedIndicatorScalarFieldEnum = {
  id: 'id',
  indicatorCode: 'indicatorCode',
  indicatorName: 'indicatorName',
  rawResult: 'rawResult',
  startDate: 'startDate',
  endDate: 'endDate',
  createdAt: 'createdAt',
  syncedToAmpathAt: 'syncedToAmpathAt',
  syncedValues: 'syncedValues',
  syncedBy: 'syncedBy'
} as const

export type StagedIndicatorScalarFieldEnum = (typeof StagedIndicatorScalarFieldEnum)[keyof typeof StagedIndicatorScalarFieldEnum]


export const ReportQueueScalarFieldEnum = {
  id: 'id',
  kenyaEmrReportUuid: 'kenyaEmrReportUuid',
  reportPeriod: 'reportPeriod',
  status: 'status',
  error: 'error',
  createdAt: 'createdAt',
  processedAt: 'processedAt'
} as const

export type ReportQueueScalarFieldEnum = (typeof ReportQueueScalarFieldEnum)[keyof typeof ReportQueueScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: 'DbNull',
  JsonNull: 'JsonNull'
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const JsonNullValueInput = {
  JsonNull: 'JsonNull'
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const JsonNullValueFilter = {
  DbNull: 'DbNull',
  JsonNull: 'JsonNull',
  AnyNull: 'AnyNull'
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const FacilityOrderByRelevanceFieldEnum = {
  name: 'name',
  location: 'location'
} as const

export type FacilityOrderByRelevanceFieldEnum = (typeof FacilityOrderByRelevanceFieldEnum)[keyof typeof FacilityOrderByRelevanceFieldEnum]


export const FacilityReportTypeOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  kenyaEmrReportUuid: 'kenyaEmrReportUuid'
} as const

export type FacilityReportTypeOrderByRelevanceFieldEnum = (typeof FacilityReportTypeOrderByRelevanceFieldEnum)[keyof typeof FacilityReportTypeOrderByRelevanceFieldEnum]


export const IndicatorOrderByRelevanceFieldEnum = {
  facilityId: 'facilityId',
  indicatorId: 'indicatorId',
  name: 'name',
  value: 'value',
  period: 'period'
} as const

export type IndicatorOrderByRelevanceFieldEnum = (typeof IndicatorOrderByRelevanceFieldEnum)[keyof typeof IndicatorOrderByRelevanceFieldEnum]


export const LineListOrderByRelevanceFieldEnum = {
  facilityId: 'facilityId',
  patientId: 'patientId'
} as const

export type LineListOrderByRelevanceFieldEnum = (typeof LineListOrderByRelevanceFieldEnum)[keyof typeof LineListOrderByRelevanceFieldEnum]


export const IndicatorTypeOrderByRelevanceFieldEnum = {
  name: 'name',
  description: 'description',
  query: 'query',
  source: 'source',
  apiUrl: 'apiUrl'
} as const

export type IndicatorTypeOrderByRelevanceFieldEnum = (typeof IndicatorTypeOrderByRelevanceFieldEnum)[keyof typeof IndicatorTypeOrderByRelevanceFieldEnum]


export const StagedIndicatorOrderByRelevanceFieldEnum = {
  indicatorCode: 'indicatorCode',
  indicatorName: 'indicatorName',
  syncedBy: 'syncedBy'
} as const

export type StagedIndicatorOrderByRelevanceFieldEnum = (typeof StagedIndicatorOrderByRelevanceFieldEnum)[keyof typeof StagedIndicatorOrderByRelevanceFieldEnum]


export const ReportQueueOrderByRelevanceFieldEnum = {
  kenyaEmrReportUuid: 'kenyaEmrReportUuid',
  reportPeriod: 'reportPeriod',
  status: 'status',
  error: 'error'
} as const

export type ReportQueueOrderByRelevanceFieldEnum = (typeof ReportQueueOrderByRelevanceFieldEnum)[keyof typeof ReportQueueOrderByRelevanceFieldEnum]

