
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AmepElementstMapping` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AmepElementstMapping
 * 
 */
export type AmepElementstMappingModel = runtime.Types.Result.DefaultSelection<Prisma.$AmepElementstMappingPayload>

export type AggregateAmepElementstMapping = {
  _count: AmepElementstMappingCountAggregateOutputType | null
  _avg: AmepElementstMappingAvgAggregateOutputType | null
  _sum: AmepElementstMappingSumAggregateOutputType | null
  _min: AmepElementstMappingMinAggregateOutputType | null
  _max: AmepElementstMappingMaxAggregateOutputType | null
}

export type AmepElementstMappingAvgAggregateOutputType = {
  id: number | null
}

export type AmepElementstMappingSumAggregateOutputType = {
  id: number | null
}

export type AmepElementstMappingMinAggregateOutputType = {
  id: number | null
  kenyaEmrReportUuid: string | null
  reportVariableName: string | null
  dataElementId: string | null
  categoryOptionComboId: string | null
  attributeOptionComboId: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AmepElementstMappingMaxAggregateOutputType = {
  id: number | null
  kenyaEmrReportUuid: string | null
  reportVariableName: string | null
  dataElementId: string | null
  categoryOptionComboId: string | null
  attributeOptionComboId: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AmepElementstMappingCountAggregateOutputType = {
  id: number
  kenyaEmrReportUuid: number
  reportVariableName: number
  dataElementId: number
  categoryOptionComboId: number
  attributeOptionComboId: number
  description: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AmepElementstMappingAvgAggregateInputType = {
  id?: true
}

export type AmepElementstMappingSumAggregateInputType = {
  id?: true
}

export type AmepElementstMappingMinAggregateInputType = {
  id?: true
  kenyaEmrReportUuid?: true
  reportVariableName?: true
  dataElementId?: true
  categoryOptionComboId?: true
  attributeOptionComboId?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type AmepElementstMappingMaxAggregateInputType = {
  id?: true
  kenyaEmrReportUuid?: true
  reportVariableName?: true
  dataElementId?: true
  categoryOptionComboId?: true
  attributeOptionComboId?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type AmepElementstMappingCountAggregateInputType = {
  id?: true
  kenyaEmrReportUuid?: true
  reportVariableName?: true
  dataElementId?: true
  categoryOptionComboId?: true
  attributeOptionComboId?: true
  description?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AmepElementstMappingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AmepElementstMapping to aggregate.
   */
  where?: Prisma.AmepElementstMappingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AmepElementstMappings to fetch.
   */
  orderBy?: Prisma.AmepElementstMappingOrderByWithRelationInput | Prisma.AmepElementstMappingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AmepElementstMappingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AmepElementstMappings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AmepElementstMappings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AmepElementstMappings
  **/
  _count?: true | AmepElementstMappingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AmepElementstMappingAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AmepElementstMappingSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AmepElementstMappingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AmepElementstMappingMaxAggregateInputType
}

export type GetAmepElementstMappingAggregateType<T extends AmepElementstMappingAggregateArgs> = {
      [P in keyof T & keyof AggregateAmepElementstMapping]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAmepElementstMapping[P]>
    : Prisma.GetScalarType<T[P], AggregateAmepElementstMapping[P]>
}




export type AmepElementstMappingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AmepElementstMappingWhereInput
  orderBy?: Prisma.AmepElementstMappingOrderByWithAggregationInput | Prisma.AmepElementstMappingOrderByWithAggregationInput[]
  by: Prisma.AmepElementstMappingScalarFieldEnum[] | Prisma.AmepElementstMappingScalarFieldEnum
  having?: Prisma.AmepElementstMappingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AmepElementstMappingCountAggregateInputType | true
  _avg?: AmepElementstMappingAvgAggregateInputType
  _sum?: AmepElementstMappingSumAggregateInputType
  _min?: AmepElementstMappingMinAggregateInputType
  _max?: AmepElementstMappingMaxAggregateInputType
}

export type AmepElementstMappingGroupByOutputType = {
  id: number
  kenyaEmrReportUuid: string
  reportVariableName: string
  dataElementId: string
  categoryOptionComboId: string
  attributeOptionComboId: string | null
  description: string | null
  createdAt: Date
  updatedAt: Date
  _count: AmepElementstMappingCountAggregateOutputType | null
  _avg: AmepElementstMappingAvgAggregateOutputType | null
  _sum: AmepElementstMappingSumAggregateOutputType | null
  _min: AmepElementstMappingMinAggregateOutputType | null
  _max: AmepElementstMappingMaxAggregateOutputType | null
}

type GetAmepElementstMappingGroupByPayload<T extends AmepElementstMappingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AmepElementstMappingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AmepElementstMappingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AmepElementstMappingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AmepElementstMappingGroupByOutputType[P]>
      }
    >
  >



export type AmepElementstMappingWhereInput = {
  AND?: Prisma.AmepElementstMappingWhereInput | Prisma.AmepElementstMappingWhereInput[]
  OR?: Prisma.AmepElementstMappingWhereInput[]
  NOT?: Prisma.AmepElementstMappingWhereInput | Prisma.AmepElementstMappingWhereInput[]
  id?: Prisma.IntFilter<"AmepElementstMapping"> | number
  kenyaEmrReportUuid?: Prisma.StringFilter<"AmepElementstMapping"> | string
  reportVariableName?: Prisma.StringFilter<"AmepElementstMapping"> | string
  dataElementId?: Prisma.StringFilter<"AmepElementstMapping"> | string
  categoryOptionComboId?: Prisma.StringFilter<"AmepElementstMapping"> | string
  attributeOptionComboId?: Prisma.StringNullableFilter<"AmepElementstMapping"> | string | null
  description?: Prisma.StringNullableFilter<"AmepElementstMapping"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AmepElementstMapping"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AmepElementstMapping"> | Date | string
}

export type AmepElementstMappingOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  kenyaEmrReportUuid?: Prisma.SortOrder
  reportVariableName?: Prisma.SortOrder
  dataElementId?: Prisma.SortOrder
  categoryOptionComboId?: Prisma.SortOrder
  attributeOptionComboId?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _relevance?: Prisma.AmepElementstMappingOrderByRelevanceInput
}

export type AmepElementstMappingWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  kenyaEmrReportUuid_reportVariableName_dataElementId_categoryOptionComboId?: Prisma.AmepElementstMappingKenyaEmrReportUuidReportVariableNameDataElementIdCategoryOptionComboIdCompoundUniqueInput
  AND?: Prisma.AmepElementstMappingWhereInput | Prisma.AmepElementstMappingWhereInput[]
  OR?: Prisma.AmepElementstMappingWhereInput[]
  NOT?: Prisma.AmepElementstMappingWhereInput | Prisma.AmepElementstMappingWhereInput[]
  kenyaEmrReportUuid?: Prisma.StringFilter<"AmepElementstMapping"> | string
  reportVariableName?: Prisma.StringFilter<"AmepElementstMapping"> | string
  dataElementId?: Prisma.StringFilter<"AmepElementstMapping"> | string
  categoryOptionComboId?: Prisma.StringFilter<"AmepElementstMapping"> | string
  attributeOptionComboId?: Prisma.StringNullableFilter<"AmepElementstMapping"> | string | null
  description?: Prisma.StringNullableFilter<"AmepElementstMapping"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AmepElementstMapping"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AmepElementstMapping"> | Date | string
}, "id" | "kenyaEmrReportUuid_reportVariableName_dataElementId_categoryOptionComboId">

export type AmepElementstMappingOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  kenyaEmrReportUuid?: Prisma.SortOrder
  reportVariableName?: Prisma.SortOrder
  dataElementId?: Prisma.SortOrder
  categoryOptionComboId?: Prisma.SortOrder
  attributeOptionComboId?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AmepElementstMappingCountOrderByAggregateInput
  _avg?: Prisma.AmepElementstMappingAvgOrderByAggregateInput
  _max?: Prisma.AmepElementstMappingMaxOrderByAggregateInput
  _min?: Prisma.AmepElementstMappingMinOrderByAggregateInput
  _sum?: Prisma.AmepElementstMappingSumOrderByAggregateInput
}

export type AmepElementstMappingScalarWhereWithAggregatesInput = {
  AND?: Prisma.AmepElementstMappingScalarWhereWithAggregatesInput | Prisma.AmepElementstMappingScalarWhereWithAggregatesInput[]
  OR?: Prisma.AmepElementstMappingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AmepElementstMappingScalarWhereWithAggregatesInput | Prisma.AmepElementstMappingScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"AmepElementstMapping"> | number
  kenyaEmrReportUuid?: Prisma.StringWithAggregatesFilter<"AmepElementstMapping"> | string
  reportVariableName?: Prisma.StringWithAggregatesFilter<"AmepElementstMapping"> | string
  dataElementId?: Prisma.StringWithAggregatesFilter<"AmepElementstMapping"> | string
  categoryOptionComboId?: Prisma.StringWithAggregatesFilter<"AmepElementstMapping"> | string
  attributeOptionComboId?: Prisma.StringNullableWithAggregatesFilter<"AmepElementstMapping"> | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"AmepElementstMapping"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AmepElementstMapping"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AmepElementstMapping"> | Date | string
}

export type AmepElementstMappingCreateInput = {
  kenyaEmrReportUuid: string
  reportVariableName: string
  dataElementId: string
  categoryOptionComboId: string
  attributeOptionComboId?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AmepElementstMappingUncheckedCreateInput = {
  id?: number
  kenyaEmrReportUuid: string
  reportVariableName: string
  dataElementId: string
  categoryOptionComboId: string
  attributeOptionComboId?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AmepElementstMappingUpdateInput = {
  kenyaEmrReportUuid?: Prisma.StringFieldUpdateOperationsInput | string
  reportVariableName?: Prisma.StringFieldUpdateOperationsInput | string
  dataElementId?: Prisma.StringFieldUpdateOperationsInput | string
  categoryOptionComboId?: Prisma.StringFieldUpdateOperationsInput | string
  attributeOptionComboId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AmepElementstMappingUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  kenyaEmrReportUuid?: Prisma.StringFieldUpdateOperationsInput | string
  reportVariableName?: Prisma.StringFieldUpdateOperationsInput | string
  dataElementId?: Prisma.StringFieldUpdateOperationsInput | string
  categoryOptionComboId?: Prisma.StringFieldUpdateOperationsInput | string
  attributeOptionComboId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AmepElementstMappingCreateManyInput = {
  id?: number
  kenyaEmrReportUuid: string
  reportVariableName: string
  dataElementId: string
  categoryOptionComboId: string
  attributeOptionComboId?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AmepElementstMappingUpdateManyMutationInput = {
  kenyaEmrReportUuid?: Prisma.StringFieldUpdateOperationsInput | string
  reportVariableName?: Prisma.StringFieldUpdateOperationsInput | string
  dataElementId?: Prisma.StringFieldUpdateOperationsInput | string
  categoryOptionComboId?: Prisma.StringFieldUpdateOperationsInput | string
  attributeOptionComboId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AmepElementstMappingUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  kenyaEmrReportUuid?: Prisma.StringFieldUpdateOperationsInput | string
  reportVariableName?: Prisma.StringFieldUpdateOperationsInput | string
  dataElementId?: Prisma.StringFieldUpdateOperationsInput | string
  categoryOptionComboId?: Prisma.StringFieldUpdateOperationsInput | string
  attributeOptionComboId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AmepElementstMappingOrderByRelevanceInput = {
  fields: Prisma.AmepElementstMappingOrderByRelevanceFieldEnum | Prisma.AmepElementstMappingOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type AmepElementstMappingKenyaEmrReportUuidReportVariableNameDataElementIdCategoryOptionComboIdCompoundUniqueInput = {
  kenyaEmrReportUuid: string
  reportVariableName: string
  dataElementId: string
  categoryOptionComboId: string
}

export type AmepElementstMappingCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  kenyaEmrReportUuid?: Prisma.SortOrder
  reportVariableName?: Prisma.SortOrder
  dataElementId?: Prisma.SortOrder
  categoryOptionComboId?: Prisma.SortOrder
  attributeOptionComboId?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AmepElementstMappingAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type AmepElementstMappingMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  kenyaEmrReportUuid?: Prisma.SortOrder
  reportVariableName?: Prisma.SortOrder
  dataElementId?: Prisma.SortOrder
  categoryOptionComboId?: Prisma.SortOrder
  attributeOptionComboId?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AmepElementstMappingMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  kenyaEmrReportUuid?: Prisma.SortOrder
  reportVariableName?: Prisma.SortOrder
  dataElementId?: Prisma.SortOrder
  categoryOptionComboId?: Prisma.SortOrder
  attributeOptionComboId?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AmepElementstMappingSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type AmepElementstMappingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  kenyaEmrReportUuid?: boolean
  reportVariableName?: boolean
  dataElementId?: boolean
  categoryOptionComboId?: boolean
  attributeOptionComboId?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["amepElementstMapping"]>



export type AmepElementstMappingSelectScalar = {
  id?: boolean
  kenyaEmrReportUuid?: boolean
  reportVariableName?: boolean
  dataElementId?: boolean
  categoryOptionComboId?: boolean
  attributeOptionComboId?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AmepElementstMappingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "kenyaEmrReportUuid" | "reportVariableName" | "dataElementId" | "categoryOptionComboId" | "attributeOptionComboId" | "description" | "createdAt" | "updatedAt", ExtArgs["result"]["amepElementstMapping"]>

export type $AmepElementstMappingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AmepElementstMapping"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    kenyaEmrReportUuid: string
    reportVariableName: string
    dataElementId: string
    categoryOptionComboId: string
    attributeOptionComboId: string | null
    description: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["amepElementstMapping"]>
  composites: {}
}

export type AmepElementstMappingGetPayload<S extends boolean | null | undefined | AmepElementstMappingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AmepElementstMappingPayload, S>

export type AmepElementstMappingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AmepElementstMappingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AmepElementstMappingCountAggregateInputType | true
  }

export interface AmepElementstMappingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AmepElementstMapping'], meta: { name: 'AmepElementstMapping' } }
  /**
   * Find zero or one AmepElementstMapping that matches the filter.
   * @param {AmepElementstMappingFindUniqueArgs} args - Arguments to find a AmepElementstMapping
   * @example
   * // Get one AmepElementstMapping
   * const amepElementstMapping = await prisma.amepElementstMapping.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AmepElementstMappingFindUniqueArgs>(args: Prisma.SelectSubset<T, AmepElementstMappingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AmepElementstMappingClient<runtime.Types.Result.GetResult<Prisma.$AmepElementstMappingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AmepElementstMapping that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AmepElementstMappingFindUniqueOrThrowArgs} args - Arguments to find a AmepElementstMapping
   * @example
   * // Get one AmepElementstMapping
   * const amepElementstMapping = await prisma.amepElementstMapping.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AmepElementstMappingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AmepElementstMappingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AmepElementstMappingClient<runtime.Types.Result.GetResult<Prisma.$AmepElementstMappingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AmepElementstMapping that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AmepElementstMappingFindFirstArgs} args - Arguments to find a AmepElementstMapping
   * @example
   * // Get one AmepElementstMapping
   * const amepElementstMapping = await prisma.amepElementstMapping.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AmepElementstMappingFindFirstArgs>(args?: Prisma.SelectSubset<T, AmepElementstMappingFindFirstArgs<ExtArgs>>): Prisma.Prisma__AmepElementstMappingClient<runtime.Types.Result.GetResult<Prisma.$AmepElementstMappingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AmepElementstMapping that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AmepElementstMappingFindFirstOrThrowArgs} args - Arguments to find a AmepElementstMapping
   * @example
   * // Get one AmepElementstMapping
   * const amepElementstMapping = await prisma.amepElementstMapping.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AmepElementstMappingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AmepElementstMappingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AmepElementstMappingClient<runtime.Types.Result.GetResult<Prisma.$AmepElementstMappingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AmepElementstMappings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AmepElementstMappingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AmepElementstMappings
   * const amepElementstMappings = await prisma.amepElementstMapping.findMany()
   * 
   * // Get first 10 AmepElementstMappings
   * const amepElementstMappings = await prisma.amepElementstMapping.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const amepElementstMappingWithIdOnly = await prisma.amepElementstMapping.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AmepElementstMappingFindManyArgs>(args?: Prisma.SelectSubset<T, AmepElementstMappingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AmepElementstMappingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AmepElementstMapping.
   * @param {AmepElementstMappingCreateArgs} args - Arguments to create a AmepElementstMapping.
   * @example
   * // Create one AmepElementstMapping
   * const AmepElementstMapping = await prisma.amepElementstMapping.create({
   *   data: {
   *     // ... data to create a AmepElementstMapping
   *   }
   * })
   * 
   */
  create<T extends AmepElementstMappingCreateArgs>(args: Prisma.SelectSubset<T, AmepElementstMappingCreateArgs<ExtArgs>>): Prisma.Prisma__AmepElementstMappingClient<runtime.Types.Result.GetResult<Prisma.$AmepElementstMappingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AmepElementstMappings.
   * @param {AmepElementstMappingCreateManyArgs} args - Arguments to create many AmepElementstMappings.
   * @example
   * // Create many AmepElementstMappings
   * const amepElementstMapping = await prisma.amepElementstMapping.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AmepElementstMappingCreateManyArgs>(args?: Prisma.SelectSubset<T, AmepElementstMappingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a AmepElementstMapping.
   * @param {AmepElementstMappingDeleteArgs} args - Arguments to delete one AmepElementstMapping.
   * @example
   * // Delete one AmepElementstMapping
   * const AmepElementstMapping = await prisma.amepElementstMapping.delete({
   *   where: {
   *     // ... filter to delete one AmepElementstMapping
   *   }
   * })
   * 
   */
  delete<T extends AmepElementstMappingDeleteArgs>(args: Prisma.SelectSubset<T, AmepElementstMappingDeleteArgs<ExtArgs>>): Prisma.Prisma__AmepElementstMappingClient<runtime.Types.Result.GetResult<Prisma.$AmepElementstMappingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AmepElementstMapping.
   * @param {AmepElementstMappingUpdateArgs} args - Arguments to update one AmepElementstMapping.
   * @example
   * // Update one AmepElementstMapping
   * const amepElementstMapping = await prisma.amepElementstMapping.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AmepElementstMappingUpdateArgs>(args: Prisma.SelectSubset<T, AmepElementstMappingUpdateArgs<ExtArgs>>): Prisma.Prisma__AmepElementstMappingClient<runtime.Types.Result.GetResult<Prisma.$AmepElementstMappingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AmepElementstMappings.
   * @param {AmepElementstMappingDeleteManyArgs} args - Arguments to filter AmepElementstMappings to delete.
   * @example
   * // Delete a few AmepElementstMappings
   * const { count } = await prisma.amepElementstMapping.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AmepElementstMappingDeleteManyArgs>(args?: Prisma.SelectSubset<T, AmepElementstMappingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AmepElementstMappings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AmepElementstMappingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AmepElementstMappings
   * const amepElementstMapping = await prisma.amepElementstMapping.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AmepElementstMappingUpdateManyArgs>(args: Prisma.SelectSubset<T, AmepElementstMappingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one AmepElementstMapping.
   * @param {AmepElementstMappingUpsertArgs} args - Arguments to update or create a AmepElementstMapping.
   * @example
   * // Update or create a AmepElementstMapping
   * const amepElementstMapping = await prisma.amepElementstMapping.upsert({
   *   create: {
   *     // ... data to create a AmepElementstMapping
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AmepElementstMapping we want to update
   *   }
   * })
   */
  upsert<T extends AmepElementstMappingUpsertArgs>(args: Prisma.SelectSubset<T, AmepElementstMappingUpsertArgs<ExtArgs>>): Prisma.Prisma__AmepElementstMappingClient<runtime.Types.Result.GetResult<Prisma.$AmepElementstMappingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AmepElementstMappings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AmepElementstMappingCountArgs} args - Arguments to filter AmepElementstMappings to count.
   * @example
   * // Count the number of AmepElementstMappings
   * const count = await prisma.amepElementstMapping.count({
   *   where: {
   *     // ... the filter for the AmepElementstMappings we want to count
   *   }
   * })
  **/
  count<T extends AmepElementstMappingCountArgs>(
    args?: Prisma.Subset<T, AmepElementstMappingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AmepElementstMappingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AmepElementstMapping.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AmepElementstMappingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AmepElementstMappingAggregateArgs>(args: Prisma.Subset<T, AmepElementstMappingAggregateArgs>): Prisma.PrismaPromise<GetAmepElementstMappingAggregateType<T>>

  /**
   * Group by AmepElementstMapping.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AmepElementstMappingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AmepElementstMappingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AmepElementstMappingGroupByArgs['orderBy'] }
      : { orderBy?: AmepElementstMappingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AmepElementstMappingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAmepElementstMappingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AmepElementstMapping model
 */
readonly fields: AmepElementstMappingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AmepElementstMapping.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AmepElementstMappingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AmepElementstMapping model
 */
export interface AmepElementstMappingFieldRefs {
  readonly id: Prisma.FieldRef<"AmepElementstMapping", 'Int'>
  readonly kenyaEmrReportUuid: Prisma.FieldRef<"AmepElementstMapping", 'String'>
  readonly reportVariableName: Prisma.FieldRef<"AmepElementstMapping", 'String'>
  readonly dataElementId: Prisma.FieldRef<"AmepElementstMapping", 'String'>
  readonly categoryOptionComboId: Prisma.FieldRef<"AmepElementstMapping", 'String'>
  readonly attributeOptionComboId: Prisma.FieldRef<"AmepElementstMapping", 'String'>
  readonly description: Prisma.FieldRef<"AmepElementstMapping", 'String'>
  readonly createdAt: Prisma.FieldRef<"AmepElementstMapping", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AmepElementstMapping", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AmepElementstMapping findUnique
 */
export type AmepElementstMappingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AmepElementstMapping
   */
  select?: Prisma.AmepElementstMappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AmepElementstMapping
   */
  omit?: Prisma.AmepElementstMappingOmit<ExtArgs> | null
  /**
   * Filter, which AmepElementstMapping to fetch.
   */
  where: Prisma.AmepElementstMappingWhereUniqueInput
}

/**
 * AmepElementstMapping findUniqueOrThrow
 */
export type AmepElementstMappingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AmepElementstMapping
   */
  select?: Prisma.AmepElementstMappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AmepElementstMapping
   */
  omit?: Prisma.AmepElementstMappingOmit<ExtArgs> | null
  /**
   * Filter, which AmepElementstMapping to fetch.
   */
  where: Prisma.AmepElementstMappingWhereUniqueInput
}

/**
 * AmepElementstMapping findFirst
 */
export type AmepElementstMappingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AmepElementstMapping
   */
  select?: Prisma.AmepElementstMappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AmepElementstMapping
   */
  omit?: Prisma.AmepElementstMappingOmit<ExtArgs> | null
  /**
   * Filter, which AmepElementstMapping to fetch.
   */
  where?: Prisma.AmepElementstMappingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AmepElementstMappings to fetch.
   */
  orderBy?: Prisma.AmepElementstMappingOrderByWithRelationInput | Prisma.AmepElementstMappingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AmepElementstMappings.
   */
  cursor?: Prisma.AmepElementstMappingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AmepElementstMappings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AmepElementstMappings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AmepElementstMappings.
   */
  distinct?: Prisma.AmepElementstMappingScalarFieldEnum | Prisma.AmepElementstMappingScalarFieldEnum[]
}

/**
 * AmepElementstMapping findFirstOrThrow
 */
export type AmepElementstMappingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AmepElementstMapping
   */
  select?: Prisma.AmepElementstMappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AmepElementstMapping
   */
  omit?: Prisma.AmepElementstMappingOmit<ExtArgs> | null
  /**
   * Filter, which AmepElementstMapping to fetch.
   */
  where?: Prisma.AmepElementstMappingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AmepElementstMappings to fetch.
   */
  orderBy?: Prisma.AmepElementstMappingOrderByWithRelationInput | Prisma.AmepElementstMappingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AmepElementstMappings.
   */
  cursor?: Prisma.AmepElementstMappingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AmepElementstMappings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AmepElementstMappings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AmepElementstMappings.
   */
  distinct?: Prisma.AmepElementstMappingScalarFieldEnum | Prisma.AmepElementstMappingScalarFieldEnum[]
}

/**
 * AmepElementstMapping findMany
 */
export type AmepElementstMappingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AmepElementstMapping
   */
  select?: Prisma.AmepElementstMappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AmepElementstMapping
   */
  omit?: Prisma.AmepElementstMappingOmit<ExtArgs> | null
  /**
   * Filter, which AmepElementstMappings to fetch.
   */
  where?: Prisma.AmepElementstMappingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AmepElementstMappings to fetch.
   */
  orderBy?: Prisma.AmepElementstMappingOrderByWithRelationInput | Prisma.AmepElementstMappingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AmepElementstMappings.
   */
  cursor?: Prisma.AmepElementstMappingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AmepElementstMappings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AmepElementstMappings.
   */
  skip?: number
  distinct?: Prisma.AmepElementstMappingScalarFieldEnum | Prisma.AmepElementstMappingScalarFieldEnum[]
}

/**
 * AmepElementstMapping create
 */
export type AmepElementstMappingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AmepElementstMapping
   */
  select?: Prisma.AmepElementstMappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AmepElementstMapping
   */
  omit?: Prisma.AmepElementstMappingOmit<ExtArgs> | null
  /**
   * The data needed to create a AmepElementstMapping.
   */
  data: Prisma.XOR<Prisma.AmepElementstMappingCreateInput, Prisma.AmepElementstMappingUncheckedCreateInput>
}

/**
 * AmepElementstMapping createMany
 */
export type AmepElementstMappingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AmepElementstMappings.
   */
  data: Prisma.AmepElementstMappingCreateManyInput | Prisma.AmepElementstMappingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AmepElementstMapping update
 */
export type AmepElementstMappingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AmepElementstMapping
   */
  select?: Prisma.AmepElementstMappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AmepElementstMapping
   */
  omit?: Prisma.AmepElementstMappingOmit<ExtArgs> | null
  /**
   * The data needed to update a AmepElementstMapping.
   */
  data: Prisma.XOR<Prisma.AmepElementstMappingUpdateInput, Prisma.AmepElementstMappingUncheckedUpdateInput>
  /**
   * Choose, which AmepElementstMapping to update.
   */
  where: Prisma.AmepElementstMappingWhereUniqueInput
}

/**
 * AmepElementstMapping updateMany
 */
export type AmepElementstMappingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AmepElementstMappings.
   */
  data: Prisma.XOR<Prisma.AmepElementstMappingUpdateManyMutationInput, Prisma.AmepElementstMappingUncheckedUpdateManyInput>
  /**
   * Filter which AmepElementstMappings to update
   */
  where?: Prisma.AmepElementstMappingWhereInput
  /**
   * Limit how many AmepElementstMappings to update.
   */
  limit?: number
}

/**
 * AmepElementstMapping upsert
 */
export type AmepElementstMappingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AmepElementstMapping
   */
  select?: Prisma.AmepElementstMappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AmepElementstMapping
   */
  omit?: Prisma.AmepElementstMappingOmit<ExtArgs> | null
  /**
   * The filter to search for the AmepElementstMapping to update in case it exists.
   */
  where: Prisma.AmepElementstMappingWhereUniqueInput
  /**
   * In case the AmepElementstMapping found by the `where` argument doesn't exist, create a new AmepElementstMapping with this data.
   */
  create: Prisma.XOR<Prisma.AmepElementstMappingCreateInput, Prisma.AmepElementstMappingUncheckedCreateInput>
  /**
   * In case the AmepElementstMapping was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AmepElementstMappingUpdateInput, Prisma.AmepElementstMappingUncheckedUpdateInput>
}

/**
 * AmepElementstMapping delete
 */
export type AmepElementstMappingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AmepElementstMapping
   */
  select?: Prisma.AmepElementstMappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AmepElementstMapping
   */
  omit?: Prisma.AmepElementstMappingOmit<ExtArgs> | null
  /**
   * Filter which AmepElementstMapping to delete.
   */
  where: Prisma.AmepElementstMappingWhereUniqueInput
}

/**
 * AmepElementstMapping deleteMany
 */
export type AmepElementstMappingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AmepElementstMappings to delete
   */
  where?: Prisma.AmepElementstMappingWhereInput
  /**
   * Limit how many AmepElementstMappings to delete.
   */
  limit?: number
}

/**
 * AmepElementstMapping without action
 */
export type AmepElementstMappingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AmepElementstMapping
   */
  select?: Prisma.AmepElementstMappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AmepElementstMapping
   */
  omit?: Prisma.AmepElementstMappingOmit<ExtArgs> | null
}
