
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FacilityReportType` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model FacilityReportType
 * 
 */
export type FacilityReportTypeModel = runtime.Types.Result.DefaultSelection<Prisma.$FacilityReportTypePayload>

export type AggregateFacilityReportType = {
  _count: FacilityReportTypeCountAggregateOutputType | null
  _min: FacilityReportTypeMinAggregateOutputType | null
  _max: FacilityReportTypeMaxAggregateOutputType | null
}

export type FacilityReportTypeMinAggregateOutputType = {
  id: string | null
  name: string | null
  kenyaEmrReportUuid: string | null
  reportType: $Enums.FacilityReportTypeCategory | null
  isReporting: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FacilityReportTypeMaxAggregateOutputType = {
  id: string | null
  name: string | null
  kenyaEmrReportUuid: string | null
  reportType: $Enums.FacilityReportTypeCategory | null
  isReporting: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FacilityReportTypeCountAggregateOutputType = {
  id: number
  name: number
  kenyaEmrReportUuid: number
  reportType: number
  isReporting: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type FacilityReportTypeMinAggregateInputType = {
  id?: true
  name?: true
  kenyaEmrReportUuid?: true
  reportType?: true
  isReporting?: true
  createdAt?: true
  updatedAt?: true
}

export type FacilityReportTypeMaxAggregateInputType = {
  id?: true
  name?: true
  kenyaEmrReportUuid?: true
  reportType?: true
  isReporting?: true
  createdAt?: true
  updatedAt?: true
}

export type FacilityReportTypeCountAggregateInputType = {
  id?: true
  name?: true
  kenyaEmrReportUuid?: true
  reportType?: true
  isReporting?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type FacilityReportTypeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FacilityReportType to aggregate.
   */
  where?: Prisma.FacilityReportTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FacilityReportTypes to fetch.
   */
  orderBy?: Prisma.FacilityReportTypeOrderByWithRelationInput | Prisma.FacilityReportTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FacilityReportTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FacilityReportTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FacilityReportTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FacilityReportTypes
  **/
  _count?: true | FacilityReportTypeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FacilityReportTypeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FacilityReportTypeMaxAggregateInputType
}

export type GetFacilityReportTypeAggregateType<T extends FacilityReportTypeAggregateArgs> = {
      [P in keyof T & keyof AggregateFacilityReportType]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFacilityReportType[P]>
    : Prisma.GetScalarType<T[P], AggregateFacilityReportType[P]>
}




export type FacilityReportTypeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FacilityReportTypeWhereInput
  orderBy?: Prisma.FacilityReportTypeOrderByWithAggregationInput | Prisma.FacilityReportTypeOrderByWithAggregationInput[]
  by: Prisma.FacilityReportTypeScalarFieldEnum[] | Prisma.FacilityReportTypeScalarFieldEnum
  having?: Prisma.FacilityReportTypeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FacilityReportTypeCountAggregateInputType | true
  _min?: FacilityReportTypeMinAggregateInputType
  _max?: FacilityReportTypeMaxAggregateInputType
}

export type FacilityReportTypeGroupByOutputType = {
  id: string
  name: string
  kenyaEmrReportUuid: string
  reportType: $Enums.FacilityReportTypeCategory
  isReporting: boolean
  createdAt: Date
  updatedAt: Date
  _count: FacilityReportTypeCountAggregateOutputType | null
  _min: FacilityReportTypeMinAggregateOutputType | null
  _max: FacilityReportTypeMaxAggregateOutputType | null
}

type GetFacilityReportTypeGroupByPayload<T extends FacilityReportTypeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FacilityReportTypeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FacilityReportTypeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FacilityReportTypeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FacilityReportTypeGroupByOutputType[P]>
      }
    >
  >



export type FacilityReportTypeWhereInput = {
  AND?: Prisma.FacilityReportTypeWhereInput | Prisma.FacilityReportTypeWhereInput[]
  OR?: Prisma.FacilityReportTypeWhereInput[]
  NOT?: Prisma.FacilityReportTypeWhereInput | Prisma.FacilityReportTypeWhereInput[]
  id?: Prisma.StringFilter<"FacilityReportType"> | string
  name?: Prisma.StringFilter<"FacilityReportType"> | string
  kenyaEmrReportUuid?: Prisma.StringFilter<"FacilityReportType"> | string
  reportType?: Prisma.EnumFacilityReportTypeCategoryFilter<"FacilityReportType"> | $Enums.FacilityReportTypeCategory
  isReporting?: Prisma.BoolFilter<"FacilityReportType"> | boolean
  createdAt?: Prisma.DateTimeFilter<"FacilityReportType"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FacilityReportType"> | Date | string
}

export type FacilityReportTypeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  kenyaEmrReportUuid?: Prisma.SortOrder
  reportType?: Prisma.SortOrder
  isReporting?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _relevance?: Prisma.FacilityReportTypeOrderByRelevanceInput
}

export type FacilityReportTypeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  kenyaEmrReportUuid?: string
  AND?: Prisma.FacilityReportTypeWhereInput | Prisma.FacilityReportTypeWhereInput[]
  OR?: Prisma.FacilityReportTypeWhereInput[]
  NOT?: Prisma.FacilityReportTypeWhereInput | Prisma.FacilityReportTypeWhereInput[]
  name?: Prisma.StringFilter<"FacilityReportType"> | string
  reportType?: Prisma.EnumFacilityReportTypeCategoryFilter<"FacilityReportType"> | $Enums.FacilityReportTypeCategory
  isReporting?: Prisma.BoolFilter<"FacilityReportType"> | boolean
  createdAt?: Prisma.DateTimeFilter<"FacilityReportType"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FacilityReportType"> | Date | string
}, "id" | "kenyaEmrReportUuid">

export type FacilityReportTypeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  kenyaEmrReportUuid?: Prisma.SortOrder
  reportType?: Prisma.SortOrder
  isReporting?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.FacilityReportTypeCountOrderByAggregateInput
  _max?: Prisma.FacilityReportTypeMaxOrderByAggregateInput
  _min?: Prisma.FacilityReportTypeMinOrderByAggregateInput
}

export type FacilityReportTypeScalarWhereWithAggregatesInput = {
  AND?: Prisma.FacilityReportTypeScalarWhereWithAggregatesInput | Prisma.FacilityReportTypeScalarWhereWithAggregatesInput[]
  OR?: Prisma.FacilityReportTypeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FacilityReportTypeScalarWhereWithAggregatesInput | Prisma.FacilityReportTypeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FacilityReportType"> | string
  name?: Prisma.StringWithAggregatesFilter<"FacilityReportType"> | string
  kenyaEmrReportUuid?: Prisma.StringWithAggregatesFilter<"FacilityReportType"> | string
  reportType?: Prisma.EnumFacilityReportTypeCategoryWithAggregatesFilter<"FacilityReportType"> | $Enums.FacilityReportTypeCategory
  isReporting?: Prisma.BoolWithAggregatesFilter<"FacilityReportType"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"FacilityReportType"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"FacilityReportType"> | Date | string
}

export type FacilityReportTypeCreateInput = {
  id?: string
  name: string
  kenyaEmrReportUuid: string
  reportType: $Enums.FacilityReportTypeCategory
  isReporting?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FacilityReportTypeUncheckedCreateInput = {
  id?: string
  name: string
  kenyaEmrReportUuid: string
  reportType: $Enums.FacilityReportTypeCategory
  isReporting?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FacilityReportTypeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  kenyaEmrReportUuid?: Prisma.StringFieldUpdateOperationsInput | string
  reportType?: Prisma.EnumFacilityReportTypeCategoryFieldUpdateOperationsInput | $Enums.FacilityReportTypeCategory
  isReporting?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FacilityReportTypeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  kenyaEmrReportUuid?: Prisma.StringFieldUpdateOperationsInput | string
  reportType?: Prisma.EnumFacilityReportTypeCategoryFieldUpdateOperationsInput | $Enums.FacilityReportTypeCategory
  isReporting?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FacilityReportTypeCreateManyInput = {
  id?: string
  name: string
  kenyaEmrReportUuid: string
  reportType: $Enums.FacilityReportTypeCategory
  isReporting?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FacilityReportTypeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  kenyaEmrReportUuid?: Prisma.StringFieldUpdateOperationsInput | string
  reportType?: Prisma.EnumFacilityReportTypeCategoryFieldUpdateOperationsInput | $Enums.FacilityReportTypeCategory
  isReporting?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FacilityReportTypeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  kenyaEmrReportUuid?: Prisma.StringFieldUpdateOperationsInput | string
  reportType?: Prisma.EnumFacilityReportTypeCategoryFieldUpdateOperationsInput | $Enums.FacilityReportTypeCategory
  isReporting?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FacilityReportTypeOrderByRelevanceInput = {
  fields: Prisma.FacilityReportTypeOrderByRelevanceFieldEnum | Prisma.FacilityReportTypeOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type FacilityReportTypeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  kenyaEmrReportUuid?: Prisma.SortOrder
  reportType?: Prisma.SortOrder
  isReporting?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FacilityReportTypeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  kenyaEmrReportUuid?: Prisma.SortOrder
  reportType?: Prisma.SortOrder
  isReporting?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FacilityReportTypeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  kenyaEmrReportUuid?: Prisma.SortOrder
  reportType?: Prisma.SortOrder
  isReporting?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type EnumFacilityReportTypeCategoryFieldUpdateOperationsInput = {
  set?: $Enums.FacilityReportTypeCategory
}



export type FacilityReportTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  kenyaEmrReportUuid?: boolean
  reportType?: boolean
  isReporting?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["facilityReportType"]>



export type FacilityReportTypeSelectScalar = {
  id?: boolean
  name?: boolean
  kenyaEmrReportUuid?: boolean
  reportType?: boolean
  isReporting?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type FacilityReportTypeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "kenyaEmrReportUuid" | "reportType" | "isReporting" | "createdAt" | "updatedAt", ExtArgs["result"]["facilityReportType"]>

export type $FacilityReportTypePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FacilityReportType"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    kenyaEmrReportUuid: string
    reportType: $Enums.FacilityReportTypeCategory
    isReporting: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["facilityReportType"]>
  composites: {}
}

export type FacilityReportTypeGetPayload<S extends boolean | null | undefined | FacilityReportTypeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FacilityReportTypePayload, S>

export type FacilityReportTypeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FacilityReportTypeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FacilityReportTypeCountAggregateInputType | true
  }

export interface FacilityReportTypeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FacilityReportType'], meta: { name: 'FacilityReportType' } }
  /**
   * Find zero or one FacilityReportType that matches the filter.
   * @param {FacilityReportTypeFindUniqueArgs} args - Arguments to find a FacilityReportType
   * @example
   * // Get one FacilityReportType
   * const facilityReportType = await prisma.facilityReportType.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FacilityReportTypeFindUniqueArgs>(args: Prisma.SelectSubset<T, FacilityReportTypeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FacilityReportTypeClient<runtime.Types.Result.GetResult<Prisma.$FacilityReportTypePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FacilityReportType that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FacilityReportTypeFindUniqueOrThrowArgs} args - Arguments to find a FacilityReportType
   * @example
   * // Get one FacilityReportType
   * const facilityReportType = await prisma.facilityReportType.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FacilityReportTypeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FacilityReportTypeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FacilityReportTypeClient<runtime.Types.Result.GetResult<Prisma.$FacilityReportTypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FacilityReportType that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FacilityReportTypeFindFirstArgs} args - Arguments to find a FacilityReportType
   * @example
   * // Get one FacilityReportType
   * const facilityReportType = await prisma.facilityReportType.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FacilityReportTypeFindFirstArgs>(args?: Prisma.SelectSubset<T, FacilityReportTypeFindFirstArgs<ExtArgs>>): Prisma.Prisma__FacilityReportTypeClient<runtime.Types.Result.GetResult<Prisma.$FacilityReportTypePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FacilityReportType that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FacilityReportTypeFindFirstOrThrowArgs} args - Arguments to find a FacilityReportType
   * @example
   * // Get one FacilityReportType
   * const facilityReportType = await prisma.facilityReportType.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FacilityReportTypeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FacilityReportTypeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FacilityReportTypeClient<runtime.Types.Result.GetResult<Prisma.$FacilityReportTypePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FacilityReportTypes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FacilityReportTypeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FacilityReportTypes
   * const facilityReportTypes = await prisma.facilityReportType.findMany()
   * 
   * // Get first 10 FacilityReportTypes
   * const facilityReportTypes = await prisma.facilityReportType.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const facilityReportTypeWithIdOnly = await prisma.facilityReportType.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FacilityReportTypeFindManyArgs>(args?: Prisma.SelectSubset<T, FacilityReportTypeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FacilityReportTypePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FacilityReportType.
   * @param {FacilityReportTypeCreateArgs} args - Arguments to create a FacilityReportType.
   * @example
   * // Create one FacilityReportType
   * const FacilityReportType = await prisma.facilityReportType.create({
   *   data: {
   *     // ... data to create a FacilityReportType
   *   }
   * })
   * 
   */
  create<T extends FacilityReportTypeCreateArgs>(args: Prisma.SelectSubset<T, FacilityReportTypeCreateArgs<ExtArgs>>): Prisma.Prisma__FacilityReportTypeClient<runtime.Types.Result.GetResult<Prisma.$FacilityReportTypePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FacilityReportTypes.
   * @param {FacilityReportTypeCreateManyArgs} args - Arguments to create many FacilityReportTypes.
   * @example
   * // Create many FacilityReportTypes
   * const facilityReportType = await prisma.facilityReportType.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FacilityReportTypeCreateManyArgs>(args?: Prisma.SelectSubset<T, FacilityReportTypeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a FacilityReportType.
   * @param {FacilityReportTypeDeleteArgs} args - Arguments to delete one FacilityReportType.
   * @example
   * // Delete one FacilityReportType
   * const FacilityReportType = await prisma.facilityReportType.delete({
   *   where: {
   *     // ... filter to delete one FacilityReportType
   *   }
   * })
   * 
   */
  delete<T extends FacilityReportTypeDeleteArgs>(args: Prisma.SelectSubset<T, FacilityReportTypeDeleteArgs<ExtArgs>>): Prisma.Prisma__FacilityReportTypeClient<runtime.Types.Result.GetResult<Prisma.$FacilityReportTypePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FacilityReportType.
   * @param {FacilityReportTypeUpdateArgs} args - Arguments to update one FacilityReportType.
   * @example
   * // Update one FacilityReportType
   * const facilityReportType = await prisma.facilityReportType.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FacilityReportTypeUpdateArgs>(args: Prisma.SelectSubset<T, FacilityReportTypeUpdateArgs<ExtArgs>>): Prisma.Prisma__FacilityReportTypeClient<runtime.Types.Result.GetResult<Prisma.$FacilityReportTypePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FacilityReportTypes.
   * @param {FacilityReportTypeDeleteManyArgs} args - Arguments to filter FacilityReportTypes to delete.
   * @example
   * // Delete a few FacilityReportTypes
   * const { count } = await prisma.facilityReportType.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FacilityReportTypeDeleteManyArgs>(args?: Prisma.SelectSubset<T, FacilityReportTypeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FacilityReportTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FacilityReportTypeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FacilityReportTypes
   * const facilityReportType = await prisma.facilityReportType.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FacilityReportTypeUpdateManyArgs>(args: Prisma.SelectSubset<T, FacilityReportTypeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one FacilityReportType.
   * @param {FacilityReportTypeUpsertArgs} args - Arguments to update or create a FacilityReportType.
   * @example
   * // Update or create a FacilityReportType
   * const facilityReportType = await prisma.facilityReportType.upsert({
   *   create: {
   *     // ... data to create a FacilityReportType
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FacilityReportType we want to update
   *   }
   * })
   */
  upsert<T extends FacilityReportTypeUpsertArgs>(args: Prisma.SelectSubset<T, FacilityReportTypeUpsertArgs<ExtArgs>>): Prisma.Prisma__FacilityReportTypeClient<runtime.Types.Result.GetResult<Prisma.$FacilityReportTypePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FacilityReportTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FacilityReportTypeCountArgs} args - Arguments to filter FacilityReportTypes to count.
   * @example
   * // Count the number of FacilityReportTypes
   * const count = await prisma.facilityReportType.count({
   *   where: {
   *     // ... the filter for the FacilityReportTypes we want to count
   *   }
   * })
  **/
  count<T extends FacilityReportTypeCountArgs>(
    args?: Prisma.Subset<T, FacilityReportTypeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FacilityReportTypeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FacilityReportType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FacilityReportTypeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FacilityReportTypeAggregateArgs>(args: Prisma.Subset<T, FacilityReportTypeAggregateArgs>): Prisma.PrismaPromise<GetFacilityReportTypeAggregateType<T>>

  /**
   * Group by FacilityReportType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FacilityReportTypeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FacilityReportTypeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FacilityReportTypeGroupByArgs['orderBy'] }
      : { orderBy?: FacilityReportTypeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FacilityReportTypeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFacilityReportTypeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FacilityReportType model
 */
readonly fields: FacilityReportTypeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FacilityReportType.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FacilityReportTypeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FacilityReportType model
 */
export interface FacilityReportTypeFieldRefs {
  readonly id: Prisma.FieldRef<"FacilityReportType", 'String'>
  readonly name: Prisma.FieldRef<"FacilityReportType", 'String'>
  readonly kenyaEmrReportUuid: Prisma.FieldRef<"FacilityReportType", 'String'>
  readonly reportType: Prisma.FieldRef<"FacilityReportType", 'FacilityReportTypeCategory'>
  readonly isReporting: Prisma.FieldRef<"FacilityReportType", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"FacilityReportType", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"FacilityReportType", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FacilityReportType findUnique
 */
export type FacilityReportTypeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FacilityReportType
   */
  select?: Prisma.FacilityReportTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FacilityReportType
   */
  omit?: Prisma.FacilityReportTypeOmit<ExtArgs> | null
  /**
   * Filter, which FacilityReportType to fetch.
   */
  where: Prisma.FacilityReportTypeWhereUniqueInput
}

/**
 * FacilityReportType findUniqueOrThrow
 */
export type FacilityReportTypeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FacilityReportType
   */
  select?: Prisma.FacilityReportTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FacilityReportType
   */
  omit?: Prisma.FacilityReportTypeOmit<ExtArgs> | null
  /**
   * Filter, which FacilityReportType to fetch.
   */
  where: Prisma.FacilityReportTypeWhereUniqueInput
}

/**
 * FacilityReportType findFirst
 */
export type FacilityReportTypeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FacilityReportType
   */
  select?: Prisma.FacilityReportTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FacilityReportType
   */
  omit?: Prisma.FacilityReportTypeOmit<ExtArgs> | null
  /**
   * Filter, which FacilityReportType to fetch.
   */
  where?: Prisma.FacilityReportTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FacilityReportTypes to fetch.
   */
  orderBy?: Prisma.FacilityReportTypeOrderByWithRelationInput | Prisma.FacilityReportTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FacilityReportTypes.
   */
  cursor?: Prisma.FacilityReportTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FacilityReportTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FacilityReportTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FacilityReportTypes.
   */
  distinct?: Prisma.FacilityReportTypeScalarFieldEnum | Prisma.FacilityReportTypeScalarFieldEnum[]
}

/**
 * FacilityReportType findFirstOrThrow
 */
export type FacilityReportTypeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FacilityReportType
   */
  select?: Prisma.FacilityReportTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FacilityReportType
   */
  omit?: Prisma.FacilityReportTypeOmit<ExtArgs> | null
  /**
   * Filter, which FacilityReportType to fetch.
   */
  where?: Prisma.FacilityReportTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FacilityReportTypes to fetch.
   */
  orderBy?: Prisma.FacilityReportTypeOrderByWithRelationInput | Prisma.FacilityReportTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FacilityReportTypes.
   */
  cursor?: Prisma.FacilityReportTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FacilityReportTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FacilityReportTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FacilityReportTypes.
   */
  distinct?: Prisma.FacilityReportTypeScalarFieldEnum | Prisma.FacilityReportTypeScalarFieldEnum[]
}

/**
 * FacilityReportType findMany
 */
export type FacilityReportTypeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FacilityReportType
   */
  select?: Prisma.FacilityReportTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FacilityReportType
   */
  omit?: Prisma.FacilityReportTypeOmit<ExtArgs> | null
  /**
   * Filter, which FacilityReportTypes to fetch.
   */
  where?: Prisma.FacilityReportTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FacilityReportTypes to fetch.
   */
  orderBy?: Prisma.FacilityReportTypeOrderByWithRelationInput | Prisma.FacilityReportTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FacilityReportTypes.
   */
  cursor?: Prisma.FacilityReportTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FacilityReportTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FacilityReportTypes.
   */
  skip?: number
  distinct?: Prisma.FacilityReportTypeScalarFieldEnum | Prisma.FacilityReportTypeScalarFieldEnum[]
}

/**
 * FacilityReportType create
 */
export type FacilityReportTypeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FacilityReportType
   */
  select?: Prisma.FacilityReportTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FacilityReportType
   */
  omit?: Prisma.FacilityReportTypeOmit<ExtArgs> | null
  /**
   * The data needed to create a FacilityReportType.
   */
  data: Prisma.XOR<Prisma.FacilityReportTypeCreateInput, Prisma.FacilityReportTypeUncheckedCreateInput>
}

/**
 * FacilityReportType createMany
 */
export type FacilityReportTypeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FacilityReportTypes.
   */
  data: Prisma.FacilityReportTypeCreateManyInput | Prisma.FacilityReportTypeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FacilityReportType update
 */
export type FacilityReportTypeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FacilityReportType
   */
  select?: Prisma.FacilityReportTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FacilityReportType
   */
  omit?: Prisma.FacilityReportTypeOmit<ExtArgs> | null
  /**
   * The data needed to update a FacilityReportType.
   */
  data: Prisma.XOR<Prisma.FacilityReportTypeUpdateInput, Prisma.FacilityReportTypeUncheckedUpdateInput>
  /**
   * Choose, which FacilityReportType to update.
   */
  where: Prisma.FacilityReportTypeWhereUniqueInput
}

/**
 * FacilityReportType updateMany
 */
export type FacilityReportTypeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FacilityReportTypes.
   */
  data: Prisma.XOR<Prisma.FacilityReportTypeUpdateManyMutationInput, Prisma.FacilityReportTypeUncheckedUpdateManyInput>
  /**
   * Filter which FacilityReportTypes to update
   */
  where?: Prisma.FacilityReportTypeWhereInput
  /**
   * Limit how many FacilityReportTypes to update.
   */
  limit?: number
}

/**
 * FacilityReportType upsert
 */
export type FacilityReportTypeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FacilityReportType
   */
  select?: Prisma.FacilityReportTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FacilityReportType
   */
  omit?: Prisma.FacilityReportTypeOmit<ExtArgs> | null
  /**
   * The filter to search for the FacilityReportType to update in case it exists.
   */
  where: Prisma.FacilityReportTypeWhereUniqueInput
  /**
   * In case the FacilityReportType found by the `where` argument doesn't exist, create a new FacilityReportType with this data.
   */
  create: Prisma.XOR<Prisma.FacilityReportTypeCreateInput, Prisma.FacilityReportTypeUncheckedCreateInput>
  /**
   * In case the FacilityReportType was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FacilityReportTypeUpdateInput, Prisma.FacilityReportTypeUncheckedUpdateInput>
}

/**
 * FacilityReportType delete
 */
export type FacilityReportTypeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FacilityReportType
   */
  select?: Prisma.FacilityReportTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FacilityReportType
   */
  omit?: Prisma.FacilityReportTypeOmit<ExtArgs> | null
  /**
   * Filter which FacilityReportType to delete.
   */
  where: Prisma.FacilityReportTypeWhereUniqueInput
}

/**
 * FacilityReportType deleteMany
 */
export type FacilityReportTypeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FacilityReportTypes to delete
   */
  where?: Prisma.FacilityReportTypeWhereInput
  /**
   * Limit how many FacilityReportTypes to delete.
   */
  limit?: number
}

/**
 * FacilityReportType without action
 */
export type FacilityReportTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FacilityReportType
   */
  select?: Prisma.FacilityReportTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FacilityReportType
   */
  omit?: Prisma.FacilityReportTypeOmit<ExtArgs> | null
}
