
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `IndicatorType` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model IndicatorType
 * 
 */
export type IndicatorTypeModel = runtime.Types.Result.DefaultSelection<Prisma.$IndicatorTypePayload>

export type AggregateIndicatorType = {
  _count: IndicatorTypeCountAggregateOutputType | null
  _avg: IndicatorTypeAvgAggregateOutputType | null
  _sum: IndicatorTypeSumAggregateOutputType | null
  _min: IndicatorTypeMinAggregateOutputType | null
  _max: IndicatorTypeMaxAggregateOutputType | null
}

export type IndicatorTypeAvgAggregateOutputType = {
  id: number | null
}

export type IndicatorTypeSumAggregateOutputType = {
  id: number | null
}

export type IndicatorTypeMinAggregateOutputType = {
  id: number | null
  name: string | null
  description: string | null
  query: string | null
  source: string | null
  apiUrl: string | null
  active: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type IndicatorTypeMaxAggregateOutputType = {
  id: number | null
  name: string | null
  description: string | null
  query: string | null
  source: string | null
  apiUrl: string | null
  active: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type IndicatorTypeCountAggregateOutputType = {
  id: number
  name: number
  description: number
  query: number
  source: number
  apiUrl: number
  active: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type IndicatorTypeAvgAggregateInputType = {
  id?: true
}

export type IndicatorTypeSumAggregateInputType = {
  id?: true
}

export type IndicatorTypeMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
  query?: true
  source?: true
  apiUrl?: true
  active?: true
  createdAt?: true
  updatedAt?: true
}

export type IndicatorTypeMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
  query?: true
  source?: true
  apiUrl?: true
  active?: true
  createdAt?: true
  updatedAt?: true
}

export type IndicatorTypeCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  query?: true
  source?: true
  apiUrl?: true
  active?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type IndicatorTypeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which IndicatorType to aggregate.
   */
  where?: Prisma.IndicatorTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of IndicatorTypes to fetch.
   */
  orderBy?: Prisma.IndicatorTypeOrderByWithRelationInput | Prisma.IndicatorTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.IndicatorTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` IndicatorTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` IndicatorTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned IndicatorTypes
  **/
  _count?: true | IndicatorTypeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: IndicatorTypeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: IndicatorTypeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: IndicatorTypeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: IndicatorTypeMaxAggregateInputType
}

export type GetIndicatorTypeAggregateType<T extends IndicatorTypeAggregateArgs> = {
      [P in keyof T & keyof AggregateIndicatorType]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateIndicatorType[P]>
    : Prisma.GetScalarType<T[P], AggregateIndicatorType[P]>
}




export type IndicatorTypeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.IndicatorTypeWhereInput
  orderBy?: Prisma.IndicatorTypeOrderByWithAggregationInput | Prisma.IndicatorTypeOrderByWithAggregationInput[]
  by: Prisma.IndicatorTypeScalarFieldEnum[] | Prisma.IndicatorTypeScalarFieldEnum
  having?: Prisma.IndicatorTypeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: IndicatorTypeCountAggregateInputType | true
  _avg?: IndicatorTypeAvgAggregateInputType
  _sum?: IndicatorTypeSumAggregateInputType
  _min?: IndicatorTypeMinAggregateInputType
  _max?: IndicatorTypeMaxAggregateInputType
}

export type IndicatorTypeGroupByOutputType = {
  id: number
  name: string
  description: string | null
  query: string
  source: string
  apiUrl: string | null
  active: boolean
  createdAt: Date
  updatedAt: Date
  _count: IndicatorTypeCountAggregateOutputType | null
  _avg: IndicatorTypeAvgAggregateOutputType | null
  _sum: IndicatorTypeSumAggregateOutputType | null
  _min: IndicatorTypeMinAggregateOutputType | null
  _max: IndicatorTypeMaxAggregateOutputType | null
}

type GetIndicatorTypeGroupByPayload<T extends IndicatorTypeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<IndicatorTypeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof IndicatorTypeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], IndicatorTypeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], IndicatorTypeGroupByOutputType[P]>
      }
    >
  >



export type IndicatorTypeWhereInput = {
  AND?: Prisma.IndicatorTypeWhereInput | Prisma.IndicatorTypeWhereInput[]
  OR?: Prisma.IndicatorTypeWhereInput[]
  NOT?: Prisma.IndicatorTypeWhereInput | Prisma.IndicatorTypeWhereInput[]
  id?: Prisma.IntFilter<"IndicatorType"> | number
  name?: Prisma.StringFilter<"IndicatorType"> | string
  description?: Prisma.StringNullableFilter<"IndicatorType"> | string | null
  query?: Prisma.StringFilter<"IndicatorType"> | string
  source?: Prisma.StringFilter<"IndicatorType"> | string
  apiUrl?: Prisma.StringNullableFilter<"IndicatorType"> | string | null
  active?: Prisma.BoolFilter<"IndicatorType"> | boolean
  createdAt?: Prisma.DateTimeFilter<"IndicatorType"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"IndicatorType"> | Date | string
}

export type IndicatorTypeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  query?: Prisma.SortOrder
  source?: Prisma.SortOrder
  apiUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _relevance?: Prisma.IndicatorTypeOrderByRelevanceInput
}

export type IndicatorTypeWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.IndicatorTypeWhereInput | Prisma.IndicatorTypeWhereInput[]
  OR?: Prisma.IndicatorTypeWhereInput[]
  NOT?: Prisma.IndicatorTypeWhereInput | Prisma.IndicatorTypeWhereInput[]
  name?: Prisma.StringFilter<"IndicatorType"> | string
  description?: Prisma.StringNullableFilter<"IndicatorType"> | string | null
  query?: Prisma.StringFilter<"IndicatorType"> | string
  source?: Prisma.StringFilter<"IndicatorType"> | string
  apiUrl?: Prisma.StringNullableFilter<"IndicatorType"> | string | null
  active?: Prisma.BoolFilter<"IndicatorType"> | boolean
  createdAt?: Prisma.DateTimeFilter<"IndicatorType"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"IndicatorType"> | Date | string
}, "id">

export type IndicatorTypeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  query?: Prisma.SortOrder
  source?: Prisma.SortOrder
  apiUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.IndicatorTypeCountOrderByAggregateInput
  _avg?: Prisma.IndicatorTypeAvgOrderByAggregateInput
  _max?: Prisma.IndicatorTypeMaxOrderByAggregateInput
  _min?: Prisma.IndicatorTypeMinOrderByAggregateInput
  _sum?: Prisma.IndicatorTypeSumOrderByAggregateInput
}

export type IndicatorTypeScalarWhereWithAggregatesInput = {
  AND?: Prisma.IndicatorTypeScalarWhereWithAggregatesInput | Prisma.IndicatorTypeScalarWhereWithAggregatesInput[]
  OR?: Prisma.IndicatorTypeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.IndicatorTypeScalarWhereWithAggregatesInput | Prisma.IndicatorTypeScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"IndicatorType"> | number
  name?: Prisma.StringWithAggregatesFilter<"IndicatorType"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"IndicatorType"> | string | null
  query?: Prisma.StringWithAggregatesFilter<"IndicatorType"> | string
  source?: Prisma.StringWithAggregatesFilter<"IndicatorType"> | string
  apiUrl?: Prisma.StringNullableWithAggregatesFilter<"IndicatorType"> | string | null
  active?: Prisma.BoolWithAggregatesFilter<"IndicatorType"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"IndicatorType"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"IndicatorType"> | Date | string
}

export type IndicatorTypeCreateInput = {
  name: string
  description?: string | null
  query: string
  source: string
  apiUrl?: string | null
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type IndicatorTypeUncheckedCreateInput = {
  id?: number
  name: string
  description?: string | null
  query: string
  source: string
  apiUrl?: string | null
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type IndicatorTypeUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  query?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  apiUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IndicatorTypeUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  query?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  apiUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IndicatorTypeCreateManyInput = {
  id?: number
  name: string
  description?: string | null
  query: string
  source: string
  apiUrl?: string | null
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type IndicatorTypeUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  query?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  apiUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IndicatorTypeUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  query?: Prisma.StringFieldUpdateOperationsInput | string
  source?: Prisma.StringFieldUpdateOperationsInput | string
  apiUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IndicatorTypeOrderByRelevanceInput = {
  fields: Prisma.IndicatorTypeOrderByRelevanceFieldEnum | Prisma.IndicatorTypeOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type IndicatorTypeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  query?: Prisma.SortOrder
  source?: Prisma.SortOrder
  apiUrl?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type IndicatorTypeAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type IndicatorTypeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  query?: Prisma.SortOrder
  source?: Prisma.SortOrder
  apiUrl?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type IndicatorTypeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  query?: Prisma.SortOrder
  source?: Prisma.SortOrder
  apiUrl?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type IndicatorTypeSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type IndicatorTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  query?: boolean
  source?: boolean
  apiUrl?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["indicatorType"]>



export type IndicatorTypeSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
  query?: boolean
  source?: boolean
  apiUrl?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type IndicatorTypeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description" | "query" | "source" | "apiUrl" | "active" | "createdAt" | "updatedAt", ExtArgs["result"]["indicatorType"]>

export type $IndicatorTypePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "IndicatorType"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    description: string | null
    query: string
    source: string
    apiUrl: string | null
    active: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["indicatorType"]>
  composites: {}
}

export type IndicatorTypeGetPayload<S extends boolean | null | undefined | IndicatorTypeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$IndicatorTypePayload, S>

export type IndicatorTypeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<IndicatorTypeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: IndicatorTypeCountAggregateInputType | true
  }

export interface IndicatorTypeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['IndicatorType'], meta: { name: 'IndicatorType' } }
  /**
   * Find zero or one IndicatorType that matches the filter.
   * @param {IndicatorTypeFindUniqueArgs} args - Arguments to find a IndicatorType
   * @example
   * // Get one IndicatorType
   * const indicatorType = await prisma.indicatorType.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends IndicatorTypeFindUniqueArgs>(args: Prisma.SelectSubset<T, IndicatorTypeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__IndicatorTypeClient<runtime.Types.Result.GetResult<Prisma.$IndicatorTypePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one IndicatorType that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {IndicatorTypeFindUniqueOrThrowArgs} args - Arguments to find a IndicatorType
   * @example
   * // Get one IndicatorType
   * const indicatorType = await prisma.indicatorType.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends IndicatorTypeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, IndicatorTypeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__IndicatorTypeClient<runtime.Types.Result.GetResult<Prisma.$IndicatorTypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first IndicatorType that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IndicatorTypeFindFirstArgs} args - Arguments to find a IndicatorType
   * @example
   * // Get one IndicatorType
   * const indicatorType = await prisma.indicatorType.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends IndicatorTypeFindFirstArgs>(args?: Prisma.SelectSubset<T, IndicatorTypeFindFirstArgs<ExtArgs>>): Prisma.Prisma__IndicatorTypeClient<runtime.Types.Result.GetResult<Prisma.$IndicatorTypePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first IndicatorType that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IndicatorTypeFindFirstOrThrowArgs} args - Arguments to find a IndicatorType
   * @example
   * // Get one IndicatorType
   * const indicatorType = await prisma.indicatorType.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends IndicatorTypeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, IndicatorTypeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__IndicatorTypeClient<runtime.Types.Result.GetResult<Prisma.$IndicatorTypePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more IndicatorTypes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IndicatorTypeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all IndicatorTypes
   * const indicatorTypes = await prisma.indicatorType.findMany()
   * 
   * // Get first 10 IndicatorTypes
   * const indicatorTypes = await prisma.indicatorType.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const indicatorTypeWithIdOnly = await prisma.indicatorType.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends IndicatorTypeFindManyArgs>(args?: Prisma.SelectSubset<T, IndicatorTypeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IndicatorTypePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a IndicatorType.
   * @param {IndicatorTypeCreateArgs} args - Arguments to create a IndicatorType.
   * @example
   * // Create one IndicatorType
   * const IndicatorType = await prisma.indicatorType.create({
   *   data: {
   *     // ... data to create a IndicatorType
   *   }
   * })
   * 
   */
  create<T extends IndicatorTypeCreateArgs>(args: Prisma.SelectSubset<T, IndicatorTypeCreateArgs<ExtArgs>>): Prisma.Prisma__IndicatorTypeClient<runtime.Types.Result.GetResult<Prisma.$IndicatorTypePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many IndicatorTypes.
   * @param {IndicatorTypeCreateManyArgs} args - Arguments to create many IndicatorTypes.
   * @example
   * // Create many IndicatorTypes
   * const indicatorType = await prisma.indicatorType.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends IndicatorTypeCreateManyArgs>(args?: Prisma.SelectSubset<T, IndicatorTypeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a IndicatorType.
   * @param {IndicatorTypeDeleteArgs} args - Arguments to delete one IndicatorType.
   * @example
   * // Delete one IndicatorType
   * const IndicatorType = await prisma.indicatorType.delete({
   *   where: {
   *     // ... filter to delete one IndicatorType
   *   }
   * })
   * 
   */
  delete<T extends IndicatorTypeDeleteArgs>(args: Prisma.SelectSubset<T, IndicatorTypeDeleteArgs<ExtArgs>>): Prisma.Prisma__IndicatorTypeClient<runtime.Types.Result.GetResult<Prisma.$IndicatorTypePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one IndicatorType.
   * @param {IndicatorTypeUpdateArgs} args - Arguments to update one IndicatorType.
   * @example
   * // Update one IndicatorType
   * const indicatorType = await prisma.indicatorType.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends IndicatorTypeUpdateArgs>(args: Prisma.SelectSubset<T, IndicatorTypeUpdateArgs<ExtArgs>>): Prisma.Prisma__IndicatorTypeClient<runtime.Types.Result.GetResult<Prisma.$IndicatorTypePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more IndicatorTypes.
   * @param {IndicatorTypeDeleteManyArgs} args - Arguments to filter IndicatorTypes to delete.
   * @example
   * // Delete a few IndicatorTypes
   * const { count } = await prisma.indicatorType.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends IndicatorTypeDeleteManyArgs>(args?: Prisma.SelectSubset<T, IndicatorTypeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more IndicatorTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IndicatorTypeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many IndicatorTypes
   * const indicatorType = await prisma.indicatorType.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends IndicatorTypeUpdateManyArgs>(args: Prisma.SelectSubset<T, IndicatorTypeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one IndicatorType.
   * @param {IndicatorTypeUpsertArgs} args - Arguments to update or create a IndicatorType.
   * @example
   * // Update or create a IndicatorType
   * const indicatorType = await prisma.indicatorType.upsert({
   *   create: {
   *     // ... data to create a IndicatorType
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the IndicatorType we want to update
   *   }
   * })
   */
  upsert<T extends IndicatorTypeUpsertArgs>(args: Prisma.SelectSubset<T, IndicatorTypeUpsertArgs<ExtArgs>>): Prisma.Prisma__IndicatorTypeClient<runtime.Types.Result.GetResult<Prisma.$IndicatorTypePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of IndicatorTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IndicatorTypeCountArgs} args - Arguments to filter IndicatorTypes to count.
   * @example
   * // Count the number of IndicatorTypes
   * const count = await prisma.indicatorType.count({
   *   where: {
   *     // ... the filter for the IndicatorTypes we want to count
   *   }
   * })
  **/
  count<T extends IndicatorTypeCountArgs>(
    args?: Prisma.Subset<T, IndicatorTypeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], IndicatorTypeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a IndicatorType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IndicatorTypeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends IndicatorTypeAggregateArgs>(args: Prisma.Subset<T, IndicatorTypeAggregateArgs>): Prisma.PrismaPromise<GetIndicatorTypeAggregateType<T>>

  /**
   * Group by IndicatorType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IndicatorTypeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends IndicatorTypeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: IndicatorTypeGroupByArgs['orderBy'] }
      : { orderBy?: IndicatorTypeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, IndicatorTypeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetIndicatorTypeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the IndicatorType model
 */
readonly fields: IndicatorTypeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for IndicatorType.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__IndicatorTypeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the IndicatorType model
 */
export interface IndicatorTypeFieldRefs {
  readonly id: Prisma.FieldRef<"IndicatorType", 'Int'>
  readonly name: Prisma.FieldRef<"IndicatorType", 'String'>
  readonly description: Prisma.FieldRef<"IndicatorType", 'String'>
  readonly query: Prisma.FieldRef<"IndicatorType", 'String'>
  readonly source: Prisma.FieldRef<"IndicatorType", 'String'>
  readonly apiUrl: Prisma.FieldRef<"IndicatorType", 'String'>
  readonly active: Prisma.FieldRef<"IndicatorType", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"IndicatorType", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"IndicatorType", 'DateTime'>
}
    

// Custom InputTypes
/**
 * IndicatorType findUnique
 */
export type IndicatorTypeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IndicatorType
   */
  select?: Prisma.IndicatorTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IndicatorType
   */
  omit?: Prisma.IndicatorTypeOmit<ExtArgs> | null
  /**
   * Filter, which IndicatorType to fetch.
   */
  where: Prisma.IndicatorTypeWhereUniqueInput
}

/**
 * IndicatorType findUniqueOrThrow
 */
export type IndicatorTypeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IndicatorType
   */
  select?: Prisma.IndicatorTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IndicatorType
   */
  omit?: Prisma.IndicatorTypeOmit<ExtArgs> | null
  /**
   * Filter, which IndicatorType to fetch.
   */
  where: Prisma.IndicatorTypeWhereUniqueInput
}

/**
 * IndicatorType findFirst
 */
export type IndicatorTypeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IndicatorType
   */
  select?: Prisma.IndicatorTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IndicatorType
   */
  omit?: Prisma.IndicatorTypeOmit<ExtArgs> | null
  /**
   * Filter, which IndicatorType to fetch.
   */
  where?: Prisma.IndicatorTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of IndicatorTypes to fetch.
   */
  orderBy?: Prisma.IndicatorTypeOrderByWithRelationInput | Prisma.IndicatorTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for IndicatorTypes.
   */
  cursor?: Prisma.IndicatorTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` IndicatorTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` IndicatorTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of IndicatorTypes.
   */
  distinct?: Prisma.IndicatorTypeScalarFieldEnum | Prisma.IndicatorTypeScalarFieldEnum[]
}

/**
 * IndicatorType findFirstOrThrow
 */
export type IndicatorTypeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IndicatorType
   */
  select?: Prisma.IndicatorTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IndicatorType
   */
  omit?: Prisma.IndicatorTypeOmit<ExtArgs> | null
  /**
   * Filter, which IndicatorType to fetch.
   */
  where?: Prisma.IndicatorTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of IndicatorTypes to fetch.
   */
  orderBy?: Prisma.IndicatorTypeOrderByWithRelationInput | Prisma.IndicatorTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for IndicatorTypes.
   */
  cursor?: Prisma.IndicatorTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` IndicatorTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` IndicatorTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of IndicatorTypes.
   */
  distinct?: Prisma.IndicatorTypeScalarFieldEnum | Prisma.IndicatorTypeScalarFieldEnum[]
}

/**
 * IndicatorType findMany
 */
export type IndicatorTypeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IndicatorType
   */
  select?: Prisma.IndicatorTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IndicatorType
   */
  omit?: Prisma.IndicatorTypeOmit<ExtArgs> | null
  /**
   * Filter, which IndicatorTypes to fetch.
   */
  where?: Prisma.IndicatorTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of IndicatorTypes to fetch.
   */
  orderBy?: Prisma.IndicatorTypeOrderByWithRelationInput | Prisma.IndicatorTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing IndicatorTypes.
   */
  cursor?: Prisma.IndicatorTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` IndicatorTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` IndicatorTypes.
   */
  skip?: number
  distinct?: Prisma.IndicatorTypeScalarFieldEnum | Prisma.IndicatorTypeScalarFieldEnum[]
}

/**
 * IndicatorType create
 */
export type IndicatorTypeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IndicatorType
   */
  select?: Prisma.IndicatorTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IndicatorType
   */
  omit?: Prisma.IndicatorTypeOmit<ExtArgs> | null
  /**
   * The data needed to create a IndicatorType.
   */
  data: Prisma.XOR<Prisma.IndicatorTypeCreateInput, Prisma.IndicatorTypeUncheckedCreateInput>
}

/**
 * IndicatorType createMany
 */
export type IndicatorTypeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many IndicatorTypes.
   */
  data: Prisma.IndicatorTypeCreateManyInput | Prisma.IndicatorTypeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * IndicatorType update
 */
export type IndicatorTypeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IndicatorType
   */
  select?: Prisma.IndicatorTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IndicatorType
   */
  omit?: Prisma.IndicatorTypeOmit<ExtArgs> | null
  /**
   * The data needed to update a IndicatorType.
   */
  data: Prisma.XOR<Prisma.IndicatorTypeUpdateInput, Prisma.IndicatorTypeUncheckedUpdateInput>
  /**
   * Choose, which IndicatorType to update.
   */
  where: Prisma.IndicatorTypeWhereUniqueInput
}

/**
 * IndicatorType updateMany
 */
export type IndicatorTypeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update IndicatorTypes.
   */
  data: Prisma.XOR<Prisma.IndicatorTypeUpdateManyMutationInput, Prisma.IndicatorTypeUncheckedUpdateManyInput>
  /**
   * Filter which IndicatorTypes to update
   */
  where?: Prisma.IndicatorTypeWhereInput
  /**
   * Limit how many IndicatorTypes to update.
   */
  limit?: number
}

/**
 * IndicatorType upsert
 */
export type IndicatorTypeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IndicatorType
   */
  select?: Prisma.IndicatorTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IndicatorType
   */
  omit?: Prisma.IndicatorTypeOmit<ExtArgs> | null
  /**
   * The filter to search for the IndicatorType to update in case it exists.
   */
  where: Prisma.IndicatorTypeWhereUniqueInput
  /**
   * In case the IndicatorType found by the `where` argument doesn't exist, create a new IndicatorType with this data.
   */
  create: Prisma.XOR<Prisma.IndicatorTypeCreateInput, Prisma.IndicatorTypeUncheckedCreateInput>
  /**
   * In case the IndicatorType was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.IndicatorTypeUpdateInput, Prisma.IndicatorTypeUncheckedUpdateInput>
}

/**
 * IndicatorType delete
 */
export type IndicatorTypeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IndicatorType
   */
  select?: Prisma.IndicatorTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IndicatorType
   */
  omit?: Prisma.IndicatorTypeOmit<ExtArgs> | null
  /**
   * Filter which IndicatorType to delete.
   */
  where: Prisma.IndicatorTypeWhereUniqueInput
}

/**
 * IndicatorType deleteMany
 */
export type IndicatorTypeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which IndicatorTypes to delete
   */
  where?: Prisma.IndicatorTypeWhereInput
  /**
   * Limit how many IndicatorTypes to delete.
   */
  limit?: number
}

/**
 * IndicatorType without action
 */
export type IndicatorTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the IndicatorType
   */
  select?: Prisma.IndicatorTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the IndicatorType
   */
  omit?: Prisma.IndicatorTypeOmit<ExtArgs> | null
}
