
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LineList` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model LineList
 * 
 */
export type LineListModel = runtime.Types.Result.DefaultSelection<Prisma.$LineListPayload>

export type AggregateLineList = {
  _count: LineListCountAggregateOutputType | null
  _avg: LineListAvgAggregateOutputType | null
  _sum: LineListSumAggregateOutputType | null
  _min: LineListMinAggregateOutputType | null
  _max: LineListMaxAggregateOutputType | null
}

export type LineListAvgAggregateOutputType = {
  id: number | null
}

export type LineListSumAggregateOutputType = {
  id: number | null
}

export type LineListMinAggregateOutputType = {
  id: number | null
  facilityId: string | null
  patientId: string | null
  createdAt: Date | null
  synced: boolean | null
  syncedAt: Date | null
}

export type LineListMaxAggregateOutputType = {
  id: number | null
  facilityId: string | null
  patientId: string | null
  createdAt: Date | null
  synced: boolean | null
  syncedAt: Date | null
}

export type LineListCountAggregateOutputType = {
  id: number
  facilityId: number
  patientId: number
  data: number
  createdAt: number
  synced: number
  syncedAt: number
  _all: number
}


export type LineListAvgAggregateInputType = {
  id?: true
}

export type LineListSumAggregateInputType = {
  id?: true
}

export type LineListMinAggregateInputType = {
  id?: true
  facilityId?: true
  patientId?: true
  createdAt?: true
  synced?: true
  syncedAt?: true
}

export type LineListMaxAggregateInputType = {
  id?: true
  facilityId?: true
  patientId?: true
  createdAt?: true
  synced?: true
  syncedAt?: true
}

export type LineListCountAggregateInputType = {
  id?: true
  facilityId?: true
  patientId?: true
  data?: true
  createdAt?: true
  synced?: true
  syncedAt?: true
  _all?: true
}

export type LineListAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LineList to aggregate.
   */
  where?: Prisma.LineListWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LineLists to fetch.
   */
  orderBy?: Prisma.LineListOrderByWithRelationInput | Prisma.LineListOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LineListWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LineLists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LineLists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LineLists
  **/
  _count?: true | LineListCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LineListAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LineListSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LineListMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LineListMaxAggregateInputType
}

export type GetLineListAggregateType<T extends LineListAggregateArgs> = {
      [P in keyof T & keyof AggregateLineList]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLineList[P]>
    : Prisma.GetScalarType<T[P], AggregateLineList[P]>
}




export type LineListGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LineListWhereInput
  orderBy?: Prisma.LineListOrderByWithAggregationInput | Prisma.LineListOrderByWithAggregationInput[]
  by: Prisma.LineListScalarFieldEnum[] | Prisma.LineListScalarFieldEnum
  having?: Prisma.LineListScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LineListCountAggregateInputType | true
  _avg?: LineListAvgAggregateInputType
  _sum?: LineListSumAggregateInputType
  _min?: LineListMinAggregateInputType
  _max?: LineListMaxAggregateInputType
}

export type LineListGroupByOutputType = {
  id: number
  facilityId: string
  patientId: string | null
  data: runtime.JsonValue
  createdAt: Date
  synced: boolean
  syncedAt: Date | null
  _count: LineListCountAggregateOutputType | null
  _avg: LineListAvgAggregateOutputType | null
  _sum: LineListSumAggregateOutputType | null
  _min: LineListMinAggregateOutputType | null
  _max: LineListMaxAggregateOutputType | null
}

type GetLineListGroupByPayload<T extends LineListGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LineListGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LineListGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LineListGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LineListGroupByOutputType[P]>
      }
    >
  >



export type LineListWhereInput = {
  AND?: Prisma.LineListWhereInput | Prisma.LineListWhereInput[]
  OR?: Prisma.LineListWhereInput[]
  NOT?: Prisma.LineListWhereInput | Prisma.LineListWhereInput[]
  id?: Prisma.IntFilter<"LineList"> | number
  facilityId?: Prisma.StringFilter<"LineList"> | string
  patientId?: Prisma.StringNullableFilter<"LineList"> | string | null
  data?: Prisma.JsonFilter<"LineList">
  createdAt?: Prisma.DateTimeFilter<"LineList"> | Date | string
  synced?: Prisma.BoolFilter<"LineList"> | boolean
  syncedAt?: Prisma.DateTimeNullableFilter<"LineList"> | Date | string | null
}

export type LineListOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  facilityId?: Prisma.SortOrder
  patientId?: Prisma.SortOrderInput | Prisma.SortOrder
  data?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  synced?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _relevance?: Prisma.LineListOrderByRelevanceInput
}

export type LineListWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.LineListWhereInput | Prisma.LineListWhereInput[]
  OR?: Prisma.LineListWhereInput[]
  NOT?: Prisma.LineListWhereInput | Prisma.LineListWhereInput[]
  facilityId?: Prisma.StringFilter<"LineList"> | string
  patientId?: Prisma.StringNullableFilter<"LineList"> | string | null
  data?: Prisma.JsonFilter<"LineList">
  createdAt?: Prisma.DateTimeFilter<"LineList"> | Date | string
  synced?: Prisma.BoolFilter<"LineList"> | boolean
  syncedAt?: Prisma.DateTimeNullableFilter<"LineList"> | Date | string | null
}, "id">

export type LineListOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  facilityId?: Prisma.SortOrder
  patientId?: Prisma.SortOrderInput | Prisma.SortOrder
  data?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  synced?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.LineListCountOrderByAggregateInput
  _avg?: Prisma.LineListAvgOrderByAggregateInput
  _max?: Prisma.LineListMaxOrderByAggregateInput
  _min?: Prisma.LineListMinOrderByAggregateInput
  _sum?: Prisma.LineListSumOrderByAggregateInput
}

export type LineListScalarWhereWithAggregatesInput = {
  AND?: Prisma.LineListScalarWhereWithAggregatesInput | Prisma.LineListScalarWhereWithAggregatesInput[]
  OR?: Prisma.LineListScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LineListScalarWhereWithAggregatesInput | Prisma.LineListScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"LineList"> | number
  facilityId?: Prisma.StringWithAggregatesFilter<"LineList"> | string
  patientId?: Prisma.StringNullableWithAggregatesFilter<"LineList"> | string | null
  data?: Prisma.JsonWithAggregatesFilter<"LineList">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"LineList"> | Date | string
  synced?: Prisma.BoolWithAggregatesFilter<"LineList"> | boolean
  syncedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"LineList"> | Date | string | null
}

export type LineListCreateInput = {
  facilityId: string
  patientId?: string | null
  data: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  synced?: boolean
  syncedAt?: Date | string | null
}

export type LineListUncheckedCreateInput = {
  id?: number
  facilityId: string
  patientId?: string | null
  data: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  synced?: boolean
  syncedAt?: Date | string | null
}

export type LineListUpdateInput = {
  facilityId?: Prisma.StringFieldUpdateOperationsInput | string
  patientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  synced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type LineListUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  facilityId?: Prisma.StringFieldUpdateOperationsInput | string
  patientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  synced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type LineListCreateManyInput = {
  id?: number
  facilityId: string
  patientId?: string | null
  data: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  synced?: boolean
  syncedAt?: Date | string | null
}

export type LineListUpdateManyMutationInput = {
  facilityId?: Prisma.StringFieldUpdateOperationsInput | string
  patientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  synced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type LineListUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  facilityId?: Prisma.StringFieldUpdateOperationsInput | string
  patientId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  data?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  synced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type LineListOrderByRelevanceInput = {
  fields: Prisma.LineListOrderByRelevanceFieldEnum | Prisma.LineListOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type LineListCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  facilityId?: Prisma.SortOrder
  patientId?: Prisma.SortOrder
  data?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  synced?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrder
}

export type LineListAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type LineListMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  facilityId?: Prisma.SortOrder
  patientId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  synced?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrder
}

export type LineListMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  facilityId?: Prisma.SortOrder
  patientId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  synced?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrder
}

export type LineListSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type LineListSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  facilityId?: boolean
  patientId?: boolean
  data?: boolean
  createdAt?: boolean
  synced?: boolean
  syncedAt?: boolean
}, ExtArgs["result"]["lineList"]>



export type LineListSelectScalar = {
  id?: boolean
  facilityId?: boolean
  patientId?: boolean
  data?: boolean
  createdAt?: boolean
  synced?: boolean
  syncedAt?: boolean
}

export type LineListOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "facilityId" | "patientId" | "data" | "createdAt" | "synced" | "syncedAt", ExtArgs["result"]["lineList"]>

export type $LineListPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LineList"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    facilityId: string
    patientId: string | null
    data: runtime.JsonValue
    createdAt: Date
    synced: boolean
    syncedAt: Date | null
  }, ExtArgs["result"]["lineList"]>
  composites: {}
}

export type LineListGetPayload<S extends boolean | null | undefined | LineListDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LineListPayload, S>

export type LineListCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LineListFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LineListCountAggregateInputType | true
  }

export interface LineListDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LineList'], meta: { name: 'LineList' } }
  /**
   * Find zero or one LineList that matches the filter.
   * @param {LineListFindUniqueArgs} args - Arguments to find a LineList
   * @example
   * // Get one LineList
   * const lineList = await prisma.lineList.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LineListFindUniqueArgs>(args: Prisma.SelectSubset<T, LineListFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LineListClient<runtime.Types.Result.GetResult<Prisma.$LineListPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LineList that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LineListFindUniqueOrThrowArgs} args - Arguments to find a LineList
   * @example
   * // Get one LineList
   * const lineList = await prisma.lineList.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LineListFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LineListFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LineListClient<runtime.Types.Result.GetResult<Prisma.$LineListPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LineList that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LineListFindFirstArgs} args - Arguments to find a LineList
   * @example
   * // Get one LineList
   * const lineList = await prisma.lineList.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LineListFindFirstArgs>(args?: Prisma.SelectSubset<T, LineListFindFirstArgs<ExtArgs>>): Prisma.Prisma__LineListClient<runtime.Types.Result.GetResult<Prisma.$LineListPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LineList that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LineListFindFirstOrThrowArgs} args - Arguments to find a LineList
   * @example
   * // Get one LineList
   * const lineList = await prisma.lineList.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LineListFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LineListFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LineListClient<runtime.Types.Result.GetResult<Prisma.$LineListPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LineLists that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LineListFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LineLists
   * const lineLists = await prisma.lineList.findMany()
   * 
   * // Get first 10 LineLists
   * const lineLists = await prisma.lineList.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const lineListWithIdOnly = await prisma.lineList.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LineListFindManyArgs>(args?: Prisma.SelectSubset<T, LineListFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LineListPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LineList.
   * @param {LineListCreateArgs} args - Arguments to create a LineList.
   * @example
   * // Create one LineList
   * const LineList = await prisma.lineList.create({
   *   data: {
   *     // ... data to create a LineList
   *   }
   * })
   * 
   */
  create<T extends LineListCreateArgs>(args: Prisma.SelectSubset<T, LineListCreateArgs<ExtArgs>>): Prisma.Prisma__LineListClient<runtime.Types.Result.GetResult<Prisma.$LineListPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LineLists.
   * @param {LineListCreateManyArgs} args - Arguments to create many LineLists.
   * @example
   * // Create many LineLists
   * const lineList = await prisma.lineList.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LineListCreateManyArgs>(args?: Prisma.SelectSubset<T, LineListCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a LineList.
   * @param {LineListDeleteArgs} args - Arguments to delete one LineList.
   * @example
   * // Delete one LineList
   * const LineList = await prisma.lineList.delete({
   *   where: {
   *     // ... filter to delete one LineList
   *   }
   * })
   * 
   */
  delete<T extends LineListDeleteArgs>(args: Prisma.SelectSubset<T, LineListDeleteArgs<ExtArgs>>): Prisma.Prisma__LineListClient<runtime.Types.Result.GetResult<Prisma.$LineListPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LineList.
   * @param {LineListUpdateArgs} args - Arguments to update one LineList.
   * @example
   * // Update one LineList
   * const lineList = await prisma.lineList.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LineListUpdateArgs>(args: Prisma.SelectSubset<T, LineListUpdateArgs<ExtArgs>>): Prisma.Prisma__LineListClient<runtime.Types.Result.GetResult<Prisma.$LineListPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LineLists.
   * @param {LineListDeleteManyArgs} args - Arguments to filter LineLists to delete.
   * @example
   * // Delete a few LineLists
   * const { count } = await prisma.lineList.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LineListDeleteManyArgs>(args?: Prisma.SelectSubset<T, LineListDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LineLists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LineListUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LineLists
   * const lineList = await prisma.lineList.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LineListUpdateManyArgs>(args: Prisma.SelectSubset<T, LineListUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one LineList.
   * @param {LineListUpsertArgs} args - Arguments to update or create a LineList.
   * @example
   * // Update or create a LineList
   * const lineList = await prisma.lineList.upsert({
   *   create: {
   *     // ... data to create a LineList
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LineList we want to update
   *   }
   * })
   */
  upsert<T extends LineListUpsertArgs>(args: Prisma.SelectSubset<T, LineListUpsertArgs<ExtArgs>>): Prisma.Prisma__LineListClient<runtime.Types.Result.GetResult<Prisma.$LineListPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LineLists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LineListCountArgs} args - Arguments to filter LineLists to count.
   * @example
   * // Count the number of LineLists
   * const count = await prisma.lineList.count({
   *   where: {
   *     // ... the filter for the LineLists we want to count
   *   }
   * })
  **/
  count<T extends LineListCountArgs>(
    args?: Prisma.Subset<T, LineListCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LineListCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LineList.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LineListAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LineListAggregateArgs>(args: Prisma.Subset<T, LineListAggregateArgs>): Prisma.PrismaPromise<GetLineListAggregateType<T>>

  /**
   * Group by LineList.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LineListGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LineListGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LineListGroupByArgs['orderBy'] }
      : { orderBy?: LineListGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LineListGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLineListGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LineList model
 */
readonly fields: LineListFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LineList.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LineListClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LineList model
 */
export interface LineListFieldRefs {
  readonly id: Prisma.FieldRef<"LineList", 'Int'>
  readonly facilityId: Prisma.FieldRef<"LineList", 'String'>
  readonly patientId: Prisma.FieldRef<"LineList", 'String'>
  readonly data: Prisma.FieldRef<"LineList", 'Json'>
  readonly createdAt: Prisma.FieldRef<"LineList", 'DateTime'>
  readonly synced: Prisma.FieldRef<"LineList", 'Boolean'>
  readonly syncedAt: Prisma.FieldRef<"LineList", 'DateTime'>
}
    

// Custom InputTypes
/**
 * LineList findUnique
 */
export type LineListFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LineList
   */
  select?: Prisma.LineListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LineList
   */
  omit?: Prisma.LineListOmit<ExtArgs> | null
  /**
   * Filter, which LineList to fetch.
   */
  where: Prisma.LineListWhereUniqueInput
}

/**
 * LineList findUniqueOrThrow
 */
export type LineListFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LineList
   */
  select?: Prisma.LineListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LineList
   */
  omit?: Prisma.LineListOmit<ExtArgs> | null
  /**
   * Filter, which LineList to fetch.
   */
  where: Prisma.LineListWhereUniqueInput
}

/**
 * LineList findFirst
 */
export type LineListFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LineList
   */
  select?: Prisma.LineListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LineList
   */
  omit?: Prisma.LineListOmit<ExtArgs> | null
  /**
   * Filter, which LineList to fetch.
   */
  where?: Prisma.LineListWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LineLists to fetch.
   */
  orderBy?: Prisma.LineListOrderByWithRelationInput | Prisma.LineListOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LineLists.
   */
  cursor?: Prisma.LineListWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LineLists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LineLists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LineLists.
   */
  distinct?: Prisma.LineListScalarFieldEnum | Prisma.LineListScalarFieldEnum[]
}

/**
 * LineList findFirstOrThrow
 */
export type LineListFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LineList
   */
  select?: Prisma.LineListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LineList
   */
  omit?: Prisma.LineListOmit<ExtArgs> | null
  /**
   * Filter, which LineList to fetch.
   */
  where?: Prisma.LineListWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LineLists to fetch.
   */
  orderBy?: Prisma.LineListOrderByWithRelationInput | Prisma.LineListOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LineLists.
   */
  cursor?: Prisma.LineListWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LineLists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LineLists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LineLists.
   */
  distinct?: Prisma.LineListScalarFieldEnum | Prisma.LineListScalarFieldEnum[]
}

/**
 * LineList findMany
 */
export type LineListFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LineList
   */
  select?: Prisma.LineListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LineList
   */
  omit?: Prisma.LineListOmit<ExtArgs> | null
  /**
   * Filter, which LineLists to fetch.
   */
  where?: Prisma.LineListWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LineLists to fetch.
   */
  orderBy?: Prisma.LineListOrderByWithRelationInput | Prisma.LineListOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LineLists.
   */
  cursor?: Prisma.LineListWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LineLists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LineLists.
   */
  skip?: number
  distinct?: Prisma.LineListScalarFieldEnum | Prisma.LineListScalarFieldEnum[]
}

/**
 * LineList create
 */
export type LineListCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LineList
   */
  select?: Prisma.LineListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LineList
   */
  omit?: Prisma.LineListOmit<ExtArgs> | null
  /**
   * The data needed to create a LineList.
   */
  data: Prisma.XOR<Prisma.LineListCreateInput, Prisma.LineListUncheckedCreateInput>
}

/**
 * LineList createMany
 */
export type LineListCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LineLists.
   */
  data: Prisma.LineListCreateManyInput | Prisma.LineListCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LineList update
 */
export type LineListUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LineList
   */
  select?: Prisma.LineListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LineList
   */
  omit?: Prisma.LineListOmit<ExtArgs> | null
  /**
   * The data needed to update a LineList.
   */
  data: Prisma.XOR<Prisma.LineListUpdateInput, Prisma.LineListUncheckedUpdateInput>
  /**
   * Choose, which LineList to update.
   */
  where: Prisma.LineListWhereUniqueInput
}

/**
 * LineList updateMany
 */
export type LineListUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LineLists.
   */
  data: Prisma.XOR<Prisma.LineListUpdateManyMutationInput, Prisma.LineListUncheckedUpdateManyInput>
  /**
   * Filter which LineLists to update
   */
  where?: Prisma.LineListWhereInput
  /**
   * Limit how many LineLists to update.
   */
  limit?: number
}

/**
 * LineList upsert
 */
export type LineListUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LineList
   */
  select?: Prisma.LineListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LineList
   */
  omit?: Prisma.LineListOmit<ExtArgs> | null
  /**
   * The filter to search for the LineList to update in case it exists.
   */
  where: Prisma.LineListWhereUniqueInput
  /**
   * In case the LineList found by the `where` argument doesn't exist, create a new LineList with this data.
   */
  create: Prisma.XOR<Prisma.LineListCreateInput, Prisma.LineListUncheckedCreateInput>
  /**
   * In case the LineList was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LineListUpdateInput, Prisma.LineListUncheckedUpdateInput>
}

/**
 * LineList delete
 */
export type LineListDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LineList
   */
  select?: Prisma.LineListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LineList
   */
  omit?: Prisma.LineListOmit<ExtArgs> | null
  /**
   * Filter which LineList to delete.
   */
  where: Prisma.LineListWhereUniqueInput
}

/**
 * LineList deleteMany
 */
export type LineListDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LineLists to delete
   */
  where?: Prisma.LineListWhereInput
  /**
   * Limit how many LineLists to delete.
   */
  limit?: number
}

/**
 * LineList without action
 */
export type LineListDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LineList
   */
  select?: Prisma.LineListSelect<ExtArgs> | null
  /**
   * Omit specific fields from the LineList
   */
  omit?: Prisma.LineListOmit<ExtArgs> | null
}
