
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ReportingPeriod` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ReportingPeriod
 * 
 */
export type ReportingPeriodModel = runtime.Types.Result.DefaultSelection<Prisma.$ReportingPeriodPayload>

export type AggregateReportingPeriod = {
  _count: ReportingPeriodCountAggregateOutputType | null
  _avg: ReportingPeriodAvgAggregateOutputType | null
  _sum: ReportingPeriodSumAggregateOutputType | null
  _min: ReportingPeriodMinAggregateOutputType | null
  _max: ReportingPeriodMaxAggregateOutputType | null
}

export type ReportingPeriodAvgAggregateOutputType = {
  id: number | null
  year: number | null
  month: number | null
  fullName: number | null
}

export type ReportingPeriodSumAggregateOutputType = {
  id: number | null
  year: number | null
  month: number | null
  fullName: number | null
}

export type ReportingPeriodMinAggregateOutputType = {
  id: number | null
  year: number | null
  month: number | null
  fullName: number | null
  createdAt: Date | null
  deletedAt: Date | null
}

export type ReportingPeriodMaxAggregateOutputType = {
  id: number | null
  year: number | null
  month: number | null
  fullName: number | null
  createdAt: Date | null
  deletedAt: Date | null
}

export type ReportingPeriodCountAggregateOutputType = {
  id: number
  year: number
  month: number
  fullName: number
  createdAt: number
  deletedAt: number
  _all: number
}


export type ReportingPeriodAvgAggregateInputType = {
  id?: true
  year?: true
  month?: true
  fullName?: true
}

export type ReportingPeriodSumAggregateInputType = {
  id?: true
  year?: true
  month?: true
  fullName?: true
}

export type ReportingPeriodMinAggregateInputType = {
  id?: true
  year?: true
  month?: true
  fullName?: true
  createdAt?: true
  deletedAt?: true
}

export type ReportingPeriodMaxAggregateInputType = {
  id?: true
  year?: true
  month?: true
  fullName?: true
  createdAt?: true
  deletedAt?: true
}

export type ReportingPeriodCountAggregateInputType = {
  id?: true
  year?: true
  month?: true
  fullName?: true
  createdAt?: true
  deletedAt?: true
  _all?: true
}

export type ReportingPeriodAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReportingPeriod to aggregate.
   */
  where?: Prisma.ReportingPeriodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReportingPeriods to fetch.
   */
  orderBy?: Prisma.ReportingPeriodOrderByWithRelationInput | Prisma.ReportingPeriodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ReportingPeriodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReportingPeriods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReportingPeriods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ReportingPeriods
  **/
  _count?: true | ReportingPeriodCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ReportingPeriodAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ReportingPeriodSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ReportingPeriodMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ReportingPeriodMaxAggregateInputType
}

export type GetReportingPeriodAggregateType<T extends ReportingPeriodAggregateArgs> = {
      [P in keyof T & keyof AggregateReportingPeriod]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateReportingPeriod[P]>
    : Prisma.GetScalarType<T[P], AggregateReportingPeriod[P]>
}




export type ReportingPeriodGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReportingPeriodWhereInput
  orderBy?: Prisma.ReportingPeriodOrderByWithAggregationInput | Prisma.ReportingPeriodOrderByWithAggregationInput[]
  by: Prisma.ReportingPeriodScalarFieldEnum[] | Prisma.ReportingPeriodScalarFieldEnum
  having?: Prisma.ReportingPeriodScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ReportingPeriodCountAggregateInputType | true
  _avg?: ReportingPeriodAvgAggregateInputType
  _sum?: ReportingPeriodSumAggregateInputType
  _min?: ReportingPeriodMinAggregateInputType
  _max?: ReportingPeriodMaxAggregateInputType
}

export type ReportingPeriodGroupByOutputType = {
  id: number
  year: number
  month: number
  fullName: number
  createdAt: Date
  deletedAt: Date | null
  _count: ReportingPeriodCountAggregateOutputType | null
  _avg: ReportingPeriodAvgAggregateOutputType | null
  _sum: ReportingPeriodSumAggregateOutputType | null
  _min: ReportingPeriodMinAggregateOutputType | null
  _max: ReportingPeriodMaxAggregateOutputType | null
}

type GetReportingPeriodGroupByPayload<T extends ReportingPeriodGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ReportingPeriodGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ReportingPeriodGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ReportingPeriodGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ReportingPeriodGroupByOutputType[P]>
      }
    >
  >



export type ReportingPeriodWhereInput = {
  AND?: Prisma.ReportingPeriodWhereInput | Prisma.ReportingPeriodWhereInput[]
  OR?: Prisma.ReportingPeriodWhereInput[]
  NOT?: Prisma.ReportingPeriodWhereInput | Prisma.ReportingPeriodWhereInput[]
  id?: Prisma.IntFilter<"ReportingPeriod"> | number
  year?: Prisma.IntFilter<"ReportingPeriod"> | number
  month?: Prisma.IntFilter<"ReportingPeriod"> | number
  fullName?: Prisma.IntFilter<"ReportingPeriod"> | number
  createdAt?: Prisma.DateTimeFilter<"ReportingPeriod"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"ReportingPeriod"> | Date | string | null
}

export type ReportingPeriodOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  year?: Prisma.SortOrder
  month?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type ReportingPeriodWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ReportingPeriodWhereInput | Prisma.ReportingPeriodWhereInput[]
  OR?: Prisma.ReportingPeriodWhereInput[]
  NOT?: Prisma.ReportingPeriodWhereInput | Prisma.ReportingPeriodWhereInput[]
  year?: Prisma.IntFilter<"ReportingPeriod"> | number
  month?: Prisma.IntFilter<"ReportingPeriod"> | number
  fullName?: Prisma.IntFilter<"ReportingPeriod"> | number
  createdAt?: Prisma.DateTimeFilter<"ReportingPeriod"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"ReportingPeriod"> | Date | string | null
}, "id">

export type ReportingPeriodOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  year?: Prisma.SortOrder
  month?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ReportingPeriodCountOrderByAggregateInput
  _avg?: Prisma.ReportingPeriodAvgOrderByAggregateInput
  _max?: Prisma.ReportingPeriodMaxOrderByAggregateInput
  _min?: Prisma.ReportingPeriodMinOrderByAggregateInput
  _sum?: Prisma.ReportingPeriodSumOrderByAggregateInput
}

export type ReportingPeriodScalarWhereWithAggregatesInput = {
  AND?: Prisma.ReportingPeriodScalarWhereWithAggregatesInput | Prisma.ReportingPeriodScalarWhereWithAggregatesInput[]
  OR?: Prisma.ReportingPeriodScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ReportingPeriodScalarWhereWithAggregatesInput | Prisma.ReportingPeriodScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ReportingPeriod"> | number
  year?: Prisma.IntWithAggregatesFilter<"ReportingPeriod"> | number
  month?: Prisma.IntWithAggregatesFilter<"ReportingPeriod"> | number
  fullName?: Prisma.IntWithAggregatesFilter<"ReportingPeriod"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ReportingPeriod"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"ReportingPeriod"> | Date | string | null
}

export type ReportingPeriodCreateInput = {
  year: number
  month: number
  fullName: number
  createdAt?: Date | string
  deletedAt?: Date | string | null
}

export type ReportingPeriodUncheckedCreateInput = {
  id?: number
  year: number
  month: number
  fullName: number
  createdAt?: Date | string
  deletedAt?: Date | string | null
}

export type ReportingPeriodUpdateInput = {
  year?: Prisma.IntFieldUpdateOperationsInput | number
  month?: Prisma.IntFieldUpdateOperationsInput | number
  fullName?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ReportingPeriodUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  year?: Prisma.IntFieldUpdateOperationsInput | number
  month?: Prisma.IntFieldUpdateOperationsInput | number
  fullName?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ReportingPeriodCreateManyInput = {
  id?: number
  year: number
  month: number
  fullName: number
  createdAt?: Date | string
  deletedAt?: Date | string | null
}

export type ReportingPeriodUpdateManyMutationInput = {
  year?: Prisma.IntFieldUpdateOperationsInput | number
  month?: Prisma.IntFieldUpdateOperationsInput | number
  fullName?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ReportingPeriodUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  year?: Prisma.IntFieldUpdateOperationsInput | number
  month?: Prisma.IntFieldUpdateOperationsInput | number
  fullName?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ReportingPeriodCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  year?: Prisma.SortOrder
  month?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type ReportingPeriodAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  year?: Prisma.SortOrder
  month?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
}

export type ReportingPeriodMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  year?: Prisma.SortOrder
  month?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type ReportingPeriodMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  year?: Prisma.SortOrder
  month?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type ReportingPeriodSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  year?: Prisma.SortOrder
  month?: Prisma.SortOrder
  fullName?: Prisma.SortOrder
}



export type ReportingPeriodSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  year?: boolean
  month?: boolean
  fullName?: boolean
  createdAt?: boolean
  deletedAt?: boolean
}, ExtArgs["result"]["reportingPeriod"]>



export type ReportingPeriodSelectScalar = {
  id?: boolean
  year?: boolean
  month?: boolean
  fullName?: boolean
  createdAt?: boolean
  deletedAt?: boolean
}

export type ReportingPeriodOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "year" | "month" | "fullName" | "createdAt" | "deletedAt", ExtArgs["result"]["reportingPeriod"]>

export type $ReportingPeriodPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ReportingPeriod"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    year: number
    month: number
    fullName: number
    createdAt: Date
    deletedAt: Date | null
  }, ExtArgs["result"]["reportingPeriod"]>
  composites: {}
}

export type ReportingPeriodGetPayload<S extends boolean | null | undefined | ReportingPeriodDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ReportingPeriodPayload, S>

export type ReportingPeriodCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ReportingPeriodFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ReportingPeriodCountAggregateInputType | true
  }

export interface ReportingPeriodDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ReportingPeriod'], meta: { name: 'ReportingPeriod' } }
  /**
   * Find zero or one ReportingPeriod that matches the filter.
   * @param {ReportingPeriodFindUniqueArgs} args - Arguments to find a ReportingPeriod
   * @example
   * // Get one ReportingPeriod
   * const reportingPeriod = await prisma.reportingPeriod.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ReportingPeriodFindUniqueArgs>(args: Prisma.SelectSubset<T, ReportingPeriodFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ReportingPeriodClient<runtime.Types.Result.GetResult<Prisma.$ReportingPeriodPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ReportingPeriod that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ReportingPeriodFindUniqueOrThrowArgs} args - Arguments to find a ReportingPeriod
   * @example
   * // Get one ReportingPeriod
   * const reportingPeriod = await prisma.reportingPeriod.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ReportingPeriodFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ReportingPeriodFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReportingPeriodClient<runtime.Types.Result.GetResult<Prisma.$ReportingPeriodPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReportingPeriod that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReportingPeriodFindFirstArgs} args - Arguments to find a ReportingPeriod
   * @example
   * // Get one ReportingPeriod
   * const reportingPeriod = await prisma.reportingPeriod.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ReportingPeriodFindFirstArgs>(args?: Prisma.SelectSubset<T, ReportingPeriodFindFirstArgs<ExtArgs>>): Prisma.Prisma__ReportingPeriodClient<runtime.Types.Result.GetResult<Prisma.$ReportingPeriodPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReportingPeriod that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReportingPeriodFindFirstOrThrowArgs} args - Arguments to find a ReportingPeriod
   * @example
   * // Get one ReportingPeriod
   * const reportingPeriod = await prisma.reportingPeriod.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ReportingPeriodFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ReportingPeriodFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReportingPeriodClient<runtime.Types.Result.GetResult<Prisma.$ReportingPeriodPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ReportingPeriods that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReportingPeriodFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ReportingPeriods
   * const reportingPeriods = await prisma.reportingPeriod.findMany()
   * 
   * // Get first 10 ReportingPeriods
   * const reportingPeriods = await prisma.reportingPeriod.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const reportingPeriodWithIdOnly = await prisma.reportingPeriod.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ReportingPeriodFindManyArgs>(args?: Prisma.SelectSubset<T, ReportingPeriodFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReportingPeriodPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ReportingPeriod.
   * @param {ReportingPeriodCreateArgs} args - Arguments to create a ReportingPeriod.
   * @example
   * // Create one ReportingPeriod
   * const ReportingPeriod = await prisma.reportingPeriod.create({
   *   data: {
   *     // ... data to create a ReportingPeriod
   *   }
   * })
   * 
   */
  create<T extends ReportingPeriodCreateArgs>(args: Prisma.SelectSubset<T, ReportingPeriodCreateArgs<ExtArgs>>): Prisma.Prisma__ReportingPeriodClient<runtime.Types.Result.GetResult<Prisma.$ReportingPeriodPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ReportingPeriods.
   * @param {ReportingPeriodCreateManyArgs} args - Arguments to create many ReportingPeriods.
   * @example
   * // Create many ReportingPeriods
   * const reportingPeriod = await prisma.reportingPeriod.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ReportingPeriodCreateManyArgs>(args?: Prisma.SelectSubset<T, ReportingPeriodCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a ReportingPeriod.
   * @param {ReportingPeriodDeleteArgs} args - Arguments to delete one ReportingPeriod.
   * @example
   * // Delete one ReportingPeriod
   * const ReportingPeriod = await prisma.reportingPeriod.delete({
   *   where: {
   *     // ... filter to delete one ReportingPeriod
   *   }
   * })
   * 
   */
  delete<T extends ReportingPeriodDeleteArgs>(args: Prisma.SelectSubset<T, ReportingPeriodDeleteArgs<ExtArgs>>): Prisma.Prisma__ReportingPeriodClient<runtime.Types.Result.GetResult<Prisma.$ReportingPeriodPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ReportingPeriod.
   * @param {ReportingPeriodUpdateArgs} args - Arguments to update one ReportingPeriod.
   * @example
   * // Update one ReportingPeriod
   * const reportingPeriod = await prisma.reportingPeriod.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ReportingPeriodUpdateArgs>(args: Prisma.SelectSubset<T, ReportingPeriodUpdateArgs<ExtArgs>>): Prisma.Prisma__ReportingPeriodClient<runtime.Types.Result.GetResult<Prisma.$ReportingPeriodPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ReportingPeriods.
   * @param {ReportingPeriodDeleteManyArgs} args - Arguments to filter ReportingPeriods to delete.
   * @example
   * // Delete a few ReportingPeriods
   * const { count } = await prisma.reportingPeriod.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ReportingPeriodDeleteManyArgs>(args?: Prisma.SelectSubset<T, ReportingPeriodDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ReportingPeriods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReportingPeriodUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ReportingPeriods
   * const reportingPeriod = await prisma.reportingPeriod.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ReportingPeriodUpdateManyArgs>(args: Prisma.SelectSubset<T, ReportingPeriodUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one ReportingPeriod.
   * @param {ReportingPeriodUpsertArgs} args - Arguments to update or create a ReportingPeriod.
   * @example
   * // Update or create a ReportingPeriod
   * const reportingPeriod = await prisma.reportingPeriod.upsert({
   *   create: {
   *     // ... data to create a ReportingPeriod
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ReportingPeriod we want to update
   *   }
   * })
   */
  upsert<T extends ReportingPeriodUpsertArgs>(args: Prisma.SelectSubset<T, ReportingPeriodUpsertArgs<ExtArgs>>): Prisma.Prisma__ReportingPeriodClient<runtime.Types.Result.GetResult<Prisma.$ReportingPeriodPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ReportingPeriods.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReportingPeriodCountArgs} args - Arguments to filter ReportingPeriods to count.
   * @example
   * // Count the number of ReportingPeriods
   * const count = await prisma.reportingPeriod.count({
   *   where: {
   *     // ... the filter for the ReportingPeriods we want to count
   *   }
   * })
  **/
  count<T extends ReportingPeriodCountArgs>(
    args?: Prisma.Subset<T, ReportingPeriodCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ReportingPeriodCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ReportingPeriod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReportingPeriodAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ReportingPeriodAggregateArgs>(args: Prisma.Subset<T, ReportingPeriodAggregateArgs>): Prisma.PrismaPromise<GetReportingPeriodAggregateType<T>>

  /**
   * Group by ReportingPeriod.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReportingPeriodGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ReportingPeriodGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ReportingPeriodGroupByArgs['orderBy'] }
      : { orderBy?: ReportingPeriodGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ReportingPeriodGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetReportingPeriodGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ReportingPeriod model
 */
readonly fields: ReportingPeriodFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ReportingPeriod.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ReportingPeriodClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ReportingPeriod model
 */
export interface ReportingPeriodFieldRefs {
  readonly id: Prisma.FieldRef<"ReportingPeriod", 'Int'>
  readonly year: Prisma.FieldRef<"ReportingPeriod", 'Int'>
  readonly month: Prisma.FieldRef<"ReportingPeriod", 'Int'>
  readonly fullName: Prisma.FieldRef<"ReportingPeriod", 'Int'>
  readonly createdAt: Prisma.FieldRef<"ReportingPeriod", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"ReportingPeriod", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ReportingPeriod findUnique
 */
export type ReportingPeriodFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportingPeriod
   */
  select?: Prisma.ReportingPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportingPeriod
   */
  omit?: Prisma.ReportingPeriodOmit<ExtArgs> | null
  /**
   * Filter, which ReportingPeriod to fetch.
   */
  where: Prisma.ReportingPeriodWhereUniqueInput
}

/**
 * ReportingPeriod findUniqueOrThrow
 */
export type ReportingPeriodFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportingPeriod
   */
  select?: Prisma.ReportingPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportingPeriod
   */
  omit?: Prisma.ReportingPeriodOmit<ExtArgs> | null
  /**
   * Filter, which ReportingPeriod to fetch.
   */
  where: Prisma.ReportingPeriodWhereUniqueInput
}

/**
 * ReportingPeriod findFirst
 */
export type ReportingPeriodFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportingPeriod
   */
  select?: Prisma.ReportingPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportingPeriod
   */
  omit?: Prisma.ReportingPeriodOmit<ExtArgs> | null
  /**
   * Filter, which ReportingPeriod to fetch.
   */
  where?: Prisma.ReportingPeriodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReportingPeriods to fetch.
   */
  orderBy?: Prisma.ReportingPeriodOrderByWithRelationInput | Prisma.ReportingPeriodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReportingPeriods.
   */
  cursor?: Prisma.ReportingPeriodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReportingPeriods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReportingPeriods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReportingPeriods.
   */
  distinct?: Prisma.ReportingPeriodScalarFieldEnum | Prisma.ReportingPeriodScalarFieldEnum[]
}

/**
 * ReportingPeriod findFirstOrThrow
 */
export type ReportingPeriodFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportingPeriod
   */
  select?: Prisma.ReportingPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportingPeriod
   */
  omit?: Prisma.ReportingPeriodOmit<ExtArgs> | null
  /**
   * Filter, which ReportingPeriod to fetch.
   */
  where?: Prisma.ReportingPeriodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReportingPeriods to fetch.
   */
  orderBy?: Prisma.ReportingPeriodOrderByWithRelationInput | Prisma.ReportingPeriodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReportingPeriods.
   */
  cursor?: Prisma.ReportingPeriodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReportingPeriods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReportingPeriods.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReportingPeriods.
   */
  distinct?: Prisma.ReportingPeriodScalarFieldEnum | Prisma.ReportingPeriodScalarFieldEnum[]
}

/**
 * ReportingPeriod findMany
 */
export type ReportingPeriodFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportingPeriod
   */
  select?: Prisma.ReportingPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportingPeriod
   */
  omit?: Prisma.ReportingPeriodOmit<ExtArgs> | null
  /**
   * Filter, which ReportingPeriods to fetch.
   */
  where?: Prisma.ReportingPeriodWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReportingPeriods to fetch.
   */
  orderBy?: Prisma.ReportingPeriodOrderByWithRelationInput | Prisma.ReportingPeriodOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ReportingPeriods.
   */
  cursor?: Prisma.ReportingPeriodWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReportingPeriods from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReportingPeriods.
   */
  skip?: number
  distinct?: Prisma.ReportingPeriodScalarFieldEnum | Prisma.ReportingPeriodScalarFieldEnum[]
}

/**
 * ReportingPeriod create
 */
export type ReportingPeriodCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportingPeriod
   */
  select?: Prisma.ReportingPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportingPeriod
   */
  omit?: Prisma.ReportingPeriodOmit<ExtArgs> | null
  /**
   * The data needed to create a ReportingPeriod.
   */
  data: Prisma.XOR<Prisma.ReportingPeriodCreateInput, Prisma.ReportingPeriodUncheckedCreateInput>
}

/**
 * ReportingPeriod createMany
 */
export type ReportingPeriodCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ReportingPeriods.
   */
  data: Prisma.ReportingPeriodCreateManyInput | Prisma.ReportingPeriodCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ReportingPeriod update
 */
export type ReportingPeriodUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportingPeriod
   */
  select?: Prisma.ReportingPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportingPeriod
   */
  omit?: Prisma.ReportingPeriodOmit<ExtArgs> | null
  /**
   * The data needed to update a ReportingPeriod.
   */
  data: Prisma.XOR<Prisma.ReportingPeriodUpdateInput, Prisma.ReportingPeriodUncheckedUpdateInput>
  /**
   * Choose, which ReportingPeriod to update.
   */
  where: Prisma.ReportingPeriodWhereUniqueInput
}

/**
 * ReportingPeriod updateMany
 */
export type ReportingPeriodUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ReportingPeriods.
   */
  data: Prisma.XOR<Prisma.ReportingPeriodUpdateManyMutationInput, Prisma.ReportingPeriodUncheckedUpdateManyInput>
  /**
   * Filter which ReportingPeriods to update
   */
  where?: Prisma.ReportingPeriodWhereInput
  /**
   * Limit how many ReportingPeriods to update.
   */
  limit?: number
}

/**
 * ReportingPeriod upsert
 */
export type ReportingPeriodUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportingPeriod
   */
  select?: Prisma.ReportingPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportingPeriod
   */
  omit?: Prisma.ReportingPeriodOmit<ExtArgs> | null
  /**
   * The filter to search for the ReportingPeriod to update in case it exists.
   */
  where: Prisma.ReportingPeriodWhereUniqueInput
  /**
   * In case the ReportingPeriod found by the `where` argument doesn't exist, create a new ReportingPeriod with this data.
   */
  create: Prisma.XOR<Prisma.ReportingPeriodCreateInput, Prisma.ReportingPeriodUncheckedCreateInput>
  /**
   * In case the ReportingPeriod was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ReportingPeriodUpdateInput, Prisma.ReportingPeriodUncheckedUpdateInput>
}

/**
 * ReportingPeriod delete
 */
export type ReportingPeriodDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportingPeriod
   */
  select?: Prisma.ReportingPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportingPeriod
   */
  omit?: Prisma.ReportingPeriodOmit<ExtArgs> | null
  /**
   * Filter which ReportingPeriod to delete.
   */
  where: Prisma.ReportingPeriodWhereUniqueInput
}

/**
 * ReportingPeriod deleteMany
 */
export type ReportingPeriodDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReportingPeriods to delete
   */
  where?: Prisma.ReportingPeriodWhereInput
  /**
   * Limit how many ReportingPeriods to delete.
   */
  limit?: number
}

/**
 * ReportingPeriod without action
 */
export type ReportingPeriodDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportingPeriod
   */
  select?: Prisma.ReportingPeriodSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportingPeriod
   */
  omit?: Prisma.ReportingPeriodOmit<ExtArgs> | null
}
