
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ReportDownload` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ReportDownload
 * 
 */
export type ReportDownloadModel = runtime.Types.Result.DefaultSelection<Prisma.$ReportDownloadPayload>

export type AggregateReportDownload = {
  _count: ReportDownloadCountAggregateOutputType | null
  _avg: ReportDownloadAvgAggregateOutputType | null
  _sum: ReportDownloadSumAggregateOutputType | null
  _min: ReportDownloadMinAggregateOutputType | null
  _max: ReportDownloadMaxAggregateOutputType | null
}

export type ReportDownloadAvgAggregateOutputType = {
  id: number | null
  recordCount: number | null
}

export type ReportDownloadSumAggregateOutputType = {
  id: number | null
  recordCount: number | null
}

export type ReportDownloadMinAggregateOutputType = {
  id: number | null
  reportUuid: string | null
  requestUrl: string | null
  response: string | null
  reportPeriod: string | null
  requestedAt: Date | null
  recordCount: number | null
  synced: boolean | null
  syncedAt: Date | null
}

export type ReportDownloadMaxAggregateOutputType = {
  id: number | null
  reportUuid: string | null
  requestUrl: string | null
  response: string | null
  reportPeriod: string | null
  requestedAt: Date | null
  recordCount: number | null
  synced: boolean | null
  syncedAt: Date | null
}

export type ReportDownloadCountAggregateOutputType = {
  id: number
  reportUuid: number
  csvContent: number
  requestUrl: number
  response: number
  reportPeriod: number
  requestedAt: number
  recordCount: number
  synced: number
  syncedAt: number
  _all: number
}


export type ReportDownloadAvgAggregateInputType = {
  id?: true
  recordCount?: true
}

export type ReportDownloadSumAggregateInputType = {
  id?: true
  recordCount?: true
}

export type ReportDownloadMinAggregateInputType = {
  id?: true
  reportUuid?: true
  requestUrl?: true
  response?: true
  reportPeriod?: true
  requestedAt?: true
  recordCount?: true
  synced?: true
  syncedAt?: true
}

export type ReportDownloadMaxAggregateInputType = {
  id?: true
  reportUuid?: true
  requestUrl?: true
  response?: true
  reportPeriod?: true
  requestedAt?: true
  recordCount?: true
  synced?: true
  syncedAt?: true
}

export type ReportDownloadCountAggregateInputType = {
  id?: true
  reportUuid?: true
  csvContent?: true
  requestUrl?: true
  response?: true
  reportPeriod?: true
  requestedAt?: true
  recordCount?: true
  synced?: true
  syncedAt?: true
  _all?: true
}

export type ReportDownloadAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReportDownload to aggregate.
   */
  where?: Prisma.ReportDownloadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReportDownloads to fetch.
   */
  orderBy?: Prisma.ReportDownloadOrderByWithRelationInput | Prisma.ReportDownloadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ReportDownloadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReportDownloads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReportDownloads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ReportDownloads
  **/
  _count?: true | ReportDownloadCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ReportDownloadAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ReportDownloadSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ReportDownloadMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ReportDownloadMaxAggregateInputType
}

export type GetReportDownloadAggregateType<T extends ReportDownloadAggregateArgs> = {
      [P in keyof T & keyof AggregateReportDownload]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateReportDownload[P]>
    : Prisma.GetScalarType<T[P], AggregateReportDownload[P]>
}




export type ReportDownloadGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReportDownloadWhereInput
  orderBy?: Prisma.ReportDownloadOrderByWithAggregationInput | Prisma.ReportDownloadOrderByWithAggregationInput[]
  by: Prisma.ReportDownloadScalarFieldEnum[] | Prisma.ReportDownloadScalarFieldEnum
  having?: Prisma.ReportDownloadScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ReportDownloadCountAggregateInputType | true
  _avg?: ReportDownloadAvgAggregateInputType
  _sum?: ReportDownloadSumAggregateInputType
  _min?: ReportDownloadMinAggregateInputType
  _max?: ReportDownloadMaxAggregateInputType
}

export type ReportDownloadGroupByOutputType = {
  id: number
  reportUuid: string
  csvContent: runtime.JsonValue
  requestUrl: string
  response: string
  reportPeriod: string
  requestedAt: Date
  recordCount: number | null
  synced: boolean
  syncedAt: Date | null
  _count: ReportDownloadCountAggregateOutputType | null
  _avg: ReportDownloadAvgAggregateOutputType | null
  _sum: ReportDownloadSumAggregateOutputType | null
  _min: ReportDownloadMinAggregateOutputType | null
  _max: ReportDownloadMaxAggregateOutputType | null
}

type GetReportDownloadGroupByPayload<T extends ReportDownloadGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ReportDownloadGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ReportDownloadGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ReportDownloadGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ReportDownloadGroupByOutputType[P]>
      }
    >
  >



export type ReportDownloadWhereInput = {
  AND?: Prisma.ReportDownloadWhereInput | Prisma.ReportDownloadWhereInput[]
  OR?: Prisma.ReportDownloadWhereInput[]
  NOT?: Prisma.ReportDownloadWhereInput | Prisma.ReportDownloadWhereInput[]
  id?: Prisma.IntFilter<"ReportDownload"> | number
  reportUuid?: Prisma.StringFilter<"ReportDownload"> | string
  csvContent?: Prisma.JsonFilter<"ReportDownload">
  requestUrl?: Prisma.StringFilter<"ReportDownload"> | string
  response?: Prisma.StringFilter<"ReportDownload"> | string
  reportPeriod?: Prisma.StringFilter<"ReportDownload"> | string
  requestedAt?: Prisma.DateTimeFilter<"ReportDownload"> | Date | string
  recordCount?: Prisma.IntNullableFilter<"ReportDownload"> | number | null
  synced?: Prisma.BoolFilter<"ReportDownload"> | boolean
  syncedAt?: Prisma.DateTimeNullableFilter<"ReportDownload"> | Date | string | null
}

export type ReportDownloadOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  reportUuid?: Prisma.SortOrder
  csvContent?: Prisma.SortOrder
  requestUrl?: Prisma.SortOrder
  response?: Prisma.SortOrder
  reportPeriod?: Prisma.SortOrder
  requestedAt?: Prisma.SortOrder
  recordCount?: Prisma.SortOrderInput | Prisma.SortOrder
  synced?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _relevance?: Prisma.ReportDownloadOrderByRelevanceInput
}

export type ReportDownloadWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ReportDownloadWhereInput | Prisma.ReportDownloadWhereInput[]
  OR?: Prisma.ReportDownloadWhereInput[]
  NOT?: Prisma.ReportDownloadWhereInput | Prisma.ReportDownloadWhereInput[]
  reportUuid?: Prisma.StringFilter<"ReportDownload"> | string
  csvContent?: Prisma.JsonFilter<"ReportDownload">
  requestUrl?: Prisma.StringFilter<"ReportDownload"> | string
  response?: Prisma.StringFilter<"ReportDownload"> | string
  reportPeriod?: Prisma.StringFilter<"ReportDownload"> | string
  requestedAt?: Prisma.DateTimeFilter<"ReportDownload"> | Date | string
  recordCount?: Prisma.IntNullableFilter<"ReportDownload"> | number | null
  synced?: Prisma.BoolFilter<"ReportDownload"> | boolean
  syncedAt?: Prisma.DateTimeNullableFilter<"ReportDownload"> | Date | string | null
}, "id">

export type ReportDownloadOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  reportUuid?: Prisma.SortOrder
  csvContent?: Prisma.SortOrder
  requestUrl?: Prisma.SortOrder
  response?: Prisma.SortOrder
  reportPeriod?: Prisma.SortOrder
  requestedAt?: Prisma.SortOrder
  recordCount?: Prisma.SortOrderInput | Prisma.SortOrder
  synced?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ReportDownloadCountOrderByAggregateInput
  _avg?: Prisma.ReportDownloadAvgOrderByAggregateInput
  _max?: Prisma.ReportDownloadMaxOrderByAggregateInput
  _min?: Prisma.ReportDownloadMinOrderByAggregateInput
  _sum?: Prisma.ReportDownloadSumOrderByAggregateInput
}

export type ReportDownloadScalarWhereWithAggregatesInput = {
  AND?: Prisma.ReportDownloadScalarWhereWithAggregatesInput | Prisma.ReportDownloadScalarWhereWithAggregatesInput[]
  OR?: Prisma.ReportDownloadScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ReportDownloadScalarWhereWithAggregatesInput | Prisma.ReportDownloadScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ReportDownload"> | number
  reportUuid?: Prisma.StringWithAggregatesFilter<"ReportDownload"> | string
  csvContent?: Prisma.JsonWithAggregatesFilter<"ReportDownload">
  requestUrl?: Prisma.StringWithAggregatesFilter<"ReportDownload"> | string
  response?: Prisma.StringWithAggregatesFilter<"ReportDownload"> | string
  reportPeriod?: Prisma.StringWithAggregatesFilter<"ReportDownload"> | string
  requestedAt?: Prisma.DateTimeWithAggregatesFilter<"ReportDownload"> | Date | string
  recordCount?: Prisma.IntNullableWithAggregatesFilter<"ReportDownload"> | number | null
  synced?: Prisma.BoolWithAggregatesFilter<"ReportDownload"> | boolean
  syncedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"ReportDownload"> | Date | string | null
}

export type ReportDownloadCreateInput = {
  reportUuid: string
  csvContent: Prisma.JsonNullValueInput | runtime.InputJsonValue
  requestUrl: string
  response: string
  reportPeriod: string
  requestedAt?: Date | string
  recordCount?: number | null
  synced?: boolean
  syncedAt?: Date | string | null
}

export type ReportDownloadUncheckedCreateInput = {
  id?: number
  reportUuid: string
  csvContent: Prisma.JsonNullValueInput | runtime.InputJsonValue
  requestUrl: string
  response: string
  reportPeriod: string
  requestedAt?: Date | string
  recordCount?: number | null
  synced?: boolean
  syncedAt?: Date | string | null
}

export type ReportDownloadUpdateInput = {
  reportUuid?: Prisma.StringFieldUpdateOperationsInput | string
  csvContent?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  requestUrl?: Prisma.StringFieldUpdateOperationsInput | string
  response?: Prisma.StringFieldUpdateOperationsInput | string
  reportPeriod?: Prisma.StringFieldUpdateOperationsInput | string
  requestedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  recordCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  synced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ReportDownloadUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  reportUuid?: Prisma.StringFieldUpdateOperationsInput | string
  csvContent?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  requestUrl?: Prisma.StringFieldUpdateOperationsInput | string
  response?: Prisma.StringFieldUpdateOperationsInput | string
  reportPeriod?: Prisma.StringFieldUpdateOperationsInput | string
  requestedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  recordCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  synced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ReportDownloadCreateManyInput = {
  id?: number
  reportUuid: string
  csvContent: Prisma.JsonNullValueInput | runtime.InputJsonValue
  requestUrl: string
  response: string
  reportPeriod: string
  requestedAt?: Date | string
  recordCount?: number | null
  synced?: boolean
  syncedAt?: Date | string | null
}

export type ReportDownloadUpdateManyMutationInput = {
  reportUuid?: Prisma.StringFieldUpdateOperationsInput | string
  csvContent?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  requestUrl?: Prisma.StringFieldUpdateOperationsInput | string
  response?: Prisma.StringFieldUpdateOperationsInput | string
  reportPeriod?: Prisma.StringFieldUpdateOperationsInput | string
  requestedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  recordCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  synced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ReportDownloadUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  reportUuid?: Prisma.StringFieldUpdateOperationsInput | string
  csvContent?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  requestUrl?: Prisma.StringFieldUpdateOperationsInput | string
  response?: Prisma.StringFieldUpdateOperationsInput | string
  reportPeriod?: Prisma.StringFieldUpdateOperationsInput | string
  requestedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  recordCount?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  synced?: Prisma.BoolFieldUpdateOperationsInput | boolean
  syncedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ReportDownloadOrderByRelevanceInput = {
  fields: Prisma.ReportDownloadOrderByRelevanceFieldEnum | Prisma.ReportDownloadOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ReportDownloadCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  reportUuid?: Prisma.SortOrder
  csvContent?: Prisma.SortOrder
  requestUrl?: Prisma.SortOrder
  response?: Prisma.SortOrder
  reportPeriod?: Prisma.SortOrder
  requestedAt?: Prisma.SortOrder
  recordCount?: Prisma.SortOrder
  synced?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrder
}

export type ReportDownloadAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  recordCount?: Prisma.SortOrder
}

export type ReportDownloadMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  reportUuid?: Prisma.SortOrder
  requestUrl?: Prisma.SortOrder
  response?: Prisma.SortOrder
  reportPeriod?: Prisma.SortOrder
  requestedAt?: Prisma.SortOrder
  recordCount?: Prisma.SortOrder
  synced?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrder
}

export type ReportDownloadMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  reportUuid?: Prisma.SortOrder
  requestUrl?: Prisma.SortOrder
  response?: Prisma.SortOrder
  reportPeriod?: Prisma.SortOrder
  requestedAt?: Prisma.SortOrder
  recordCount?: Prisma.SortOrder
  synced?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrder
}

export type ReportDownloadSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  recordCount?: Prisma.SortOrder
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type ReportDownloadSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  reportUuid?: boolean
  csvContent?: boolean
  requestUrl?: boolean
  response?: boolean
  reportPeriod?: boolean
  requestedAt?: boolean
  recordCount?: boolean
  synced?: boolean
  syncedAt?: boolean
}, ExtArgs["result"]["reportDownload"]>



export type ReportDownloadSelectScalar = {
  id?: boolean
  reportUuid?: boolean
  csvContent?: boolean
  requestUrl?: boolean
  response?: boolean
  reportPeriod?: boolean
  requestedAt?: boolean
  recordCount?: boolean
  synced?: boolean
  syncedAt?: boolean
}

export type ReportDownloadOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "reportUuid" | "csvContent" | "requestUrl" | "response" | "reportPeriod" | "requestedAt" | "recordCount" | "synced" | "syncedAt", ExtArgs["result"]["reportDownload"]>

export type $ReportDownloadPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ReportDownload"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    reportUuid: string
    csvContent: runtime.JsonValue
    requestUrl: string
    response: string
    reportPeriod: string
    requestedAt: Date
    recordCount: number | null
    synced: boolean
    syncedAt: Date | null
  }, ExtArgs["result"]["reportDownload"]>
  composites: {}
}

export type ReportDownloadGetPayload<S extends boolean | null | undefined | ReportDownloadDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ReportDownloadPayload, S>

export type ReportDownloadCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ReportDownloadFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ReportDownloadCountAggregateInputType | true
  }

export interface ReportDownloadDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ReportDownload'], meta: { name: 'ReportDownload' } }
  /**
   * Find zero or one ReportDownload that matches the filter.
   * @param {ReportDownloadFindUniqueArgs} args - Arguments to find a ReportDownload
   * @example
   * // Get one ReportDownload
   * const reportDownload = await prisma.reportDownload.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ReportDownloadFindUniqueArgs>(args: Prisma.SelectSubset<T, ReportDownloadFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ReportDownloadClient<runtime.Types.Result.GetResult<Prisma.$ReportDownloadPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ReportDownload that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ReportDownloadFindUniqueOrThrowArgs} args - Arguments to find a ReportDownload
   * @example
   * // Get one ReportDownload
   * const reportDownload = await prisma.reportDownload.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ReportDownloadFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ReportDownloadFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReportDownloadClient<runtime.Types.Result.GetResult<Prisma.$ReportDownloadPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReportDownload that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReportDownloadFindFirstArgs} args - Arguments to find a ReportDownload
   * @example
   * // Get one ReportDownload
   * const reportDownload = await prisma.reportDownload.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ReportDownloadFindFirstArgs>(args?: Prisma.SelectSubset<T, ReportDownloadFindFirstArgs<ExtArgs>>): Prisma.Prisma__ReportDownloadClient<runtime.Types.Result.GetResult<Prisma.$ReportDownloadPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReportDownload that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReportDownloadFindFirstOrThrowArgs} args - Arguments to find a ReportDownload
   * @example
   * // Get one ReportDownload
   * const reportDownload = await prisma.reportDownload.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ReportDownloadFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ReportDownloadFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReportDownloadClient<runtime.Types.Result.GetResult<Prisma.$ReportDownloadPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ReportDownloads that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReportDownloadFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ReportDownloads
   * const reportDownloads = await prisma.reportDownload.findMany()
   * 
   * // Get first 10 ReportDownloads
   * const reportDownloads = await prisma.reportDownload.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const reportDownloadWithIdOnly = await prisma.reportDownload.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ReportDownloadFindManyArgs>(args?: Prisma.SelectSubset<T, ReportDownloadFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReportDownloadPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ReportDownload.
   * @param {ReportDownloadCreateArgs} args - Arguments to create a ReportDownload.
   * @example
   * // Create one ReportDownload
   * const ReportDownload = await prisma.reportDownload.create({
   *   data: {
   *     // ... data to create a ReportDownload
   *   }
   * })
   * 
   */
  create<T extends ReportDownloadCreateArgs>(args: Prisma.SelectSubset<T, ReportDownloadCreateArgs<ExtArgs>>): Prisma.Prisma__ReportDownloadClient<runtime.Types.Result.GetResult<Prisma.$ReportDownloadPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ReportDownloads.
   * @param {ReportDownloadCreateManyArgs} args - Arguments to create many ReportDownloads.
   * @example
   * // Create many ReportDownloads
   * const reportDownload = await prisma.reportDownload.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ReportDownloadCreateManyArgs>(args?: Prisma.SelectSubset<T, ReportDownloadCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a ReportDownload.
   * @param {ReportDownloadDeleteArgs} args - Arguments to delete one ReportDownload.
   * @example
   * // Delete one ReportDownload
   * const ReportDownload = await prisma.reportDownload.delete({
   *   where: {
   *     // ... filter to delete one ReportDownload
   *   }
   * })
   * 
   */
  delete<T extends ReportDownloadDeleteArgs>(args: Prisma.SelectSubset<T, ReportDownloadDeleteArgs<ExtArgs>>): Prisma.Prisma__ReportDownloadClient<runtime.Types.Result.GetResult<Prisma.$ReportDownloadPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ReportDownload.
   * @param {ReportDownloadUpdateArgs} args - Arguments to update one ReportDownload.
   * @example
   * // Update one ReportDownload
   * const reportDownload = await prisma.reportDownload.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ReportDownloadUpdateArgs>(args: Prisma.SelectSubset<T, ReportDownloadUpdateArgs<ExtArgs>>): Prisma.Prisma__ReportDownloadClient<runtime.Types.Result.GetResult<Prisma.$ReportDownloadPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ReportDownloads.
   * @param {ReportDownloadDeleteManyArgs} args - Arguments to filter ReportDownloads to delete.
   * @example
   * // Delete a few ReportDownloads
   * const { count } = await prisma.reportDownload.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ReportDownloadDeleteManyArgs>(args?: Prisma.SelectSubset<T, ReportDownloadDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ReportDownloads.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReportDownloadUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ReportDownloads
   * const reportDownload = await prisma.reportDownload.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ReportDownloadUpdateManyArgs>(args: Prisma.SelectSubset<T, ReportDownloadUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one ReportDownload.
   * @param {ReportDownloadUpsertArgs} args - Arguments to update or create a ReportDownload.
   * @example
   * // Update or create a ReportDownload
   * const reportDownload = await prisma.reportDownload.upsert({
   *   create: {
   *     // ... data to create a ReportDownload
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ReportDownload we want to update
   *   }
   * })
   */
  upsert<T extends ReportDownloadUpsertArgs>(args: Prisma.SelectSubset<T, ReportDownloadUpsertArgs<ExtArgs>>): Prisma.Prisma__ReportDownloadClient<runtime.Types.Result.GetResult<Prisma.$ReportDownloadPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ReportDownloads.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReportDownloadCountArgs} args - Arguments to filter ReportDownloads to count.
   * @example
   * // Count the number of ReportDownloads
   * const count = await prisma.reportDownload.count({
   *   where: {
   *     // ... the filter for the ReportDownloads we want to count
   *   }
   * })
  **/
  count<T extends ReportDownloadCountArgs>(
    args?: Prisma.Subset<T, ReportDownloadCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ReportDownloadCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ReportDownload.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReportDownloadAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ReportDownloadAggregateArgs>(args: Prisma.Subset<T, ReportDownloadAggregateArgs>): Prisma.PrismaPromise<GetReportDownloadAggregateType<T>>

  /**
   * Group by ReportDownload.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReportDownloadGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ReportDownloadGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ReportDownloadGroupByArgs['orderBy'] }
      : { orderBy?: ReportDownloadGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ReportDownloadGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetReportDownloadGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ReportDownload model
 */
readonly fields: ReportDownloadFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ReportDownload.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ReportDownloadClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ReportDownload model
 */
export interface ReportDownloadFieldRefs {
  readonly id: Prisma.FieldRef<"ReportDownload", 'Int'>
  readonly reportUuid: Prisma.FieldRef<"ReportDownload", 'String'>
  readonly csvContent: Prisma.FieldRef<"ReportDownload", 'Json'>
  readonly requestUrl: Prisma.FieldRef<"ReportDownload", 'String'>
  readonly response: Prisma.FieldRef<"ReportDownload", 'String'>
  readonly reportPeriod: Prisma.FieldRef<"ReportDownload", 'String'>
  readonly requestedAt: Prisma.FieldRef<"ReportDownload", 'DateTime'>
  readonly recordCount: Prisma.FieldRef<"ReportDownload", 'Int'>
  readonly synced: Prisma.FieldRef<"ReportDownload", 'Boolean'>
  readonly syncedAt: Prisma.FieldRef<"ReportDownload", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ReportDownload findUnique
 */
export type ReportDownloadFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportDownload
   */
  select?: Prisma.ReportDownloadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportDownload
   */
  omit?: Prisma.ReportDownloadOmit<ExtArgs> | null
  /**
   * Filter, which ReportDownload to fetch.
   */
  where: Prisma.ReportDownloadWhereUniqueInput
}

/**
 * ReportDownload findUniqueOrThrow
 */
export type ReportDownloadFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportDownload
   */
  select?: Prisma.ReportDownloadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportDownload
   */
  omit?: Prisma.ReportDownloadOmit<ExtArgs> | null
  /**
   * Filter, which ReportDownload to fetch.
   */
  where: Prisma.ReportDownloadWhereUniqueInput
}

/**
 * ReportDownload findFirst
 */
export type ReportDownloadFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportDownload
   */
  select?: Prisma.ReportDownloadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportDownload
   */
  omit?: Prisma.ReportDownloadOmit<ExtArgs> | null
  /**
   * Filter, which ReportDownload to fetch.
   */
  where?: Prisma.ReportDownloadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReportDownloads to fetch.
   */
  orderBy?: Prisma.ReportDownloadOrderByWithRelationInput | Prisma.ReportDownloadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReportDownloads.
   */
  cursor?: Prisma.ReportDownloadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReportDownloads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReportDownloads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReportDownloads.
   */
  distinct?: Prisma.ReportDownloadScalarFieldEnum | Prisma.ReportDownloadScalarFieldEnum[]
}

/**
 * ReportDownload findFirstOrThrow
 */
export type ReportDownloadFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportDownload
   */
  select?: Prisma.ReportDownloadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportDownload
   */
  omit?: Prisma.ReportDownloadOmit<ExtArgs> | null
  /**
   * Filter, which ReportDownload to fetch.
   */
  where?: Prisma.ReportDownloadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReportDownloads to fetch.
   */
  orderBy?: Prisma.ReportDownloadOrderByWithRelationInput | Prisma.ReportDownloadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReportDownloads.
   */
  cursor?: Prisma.ReportDownloadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReportDownloads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReportDownloads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReportDownloads.
   */
  distinct?: Prisma.ReportDownloadScalarFieldEnum | Prisma.ReportDownloadScalarFieldEnum[]
}

/**
 * ReportDownload findMany
 */
export type ReportDownloadFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportDownload
   */
  select?: Prisma.ReportDownloadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportDownload
   */
  omit?: Prisma.ReportDownloadOmit<ExtArgs> | null
  /**
   * Filter, which ReportDownloads to fetch.
   */
  where?: Prisma.ReportDownloadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReportDownloads to fetch.
   */
  orderBy?: Prisma.ReportDownloadOrderByWithRelationInput | Prisma.ReportDownloadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ReportDownloads.
   */
  cursor?: Prisma.ReportDownloadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReportDownloads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReportDownloads.
   */
  skip?: number
  distinct?: Prisma.ReportDownloadScalarFieldEnum | Prisma.ReportDownloadScalarFieldEnum[]
}

/**
 * ReportDownload create
 */
export type ReportDownloadCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportDownload
   */
  select?: Prisma.ReportDownloadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportDownload
   */
  omit?: Prisma.ReportDownloadOmit<ExtArgs> | null
  /**
   * The data needed to create a ReportDownload.
   */
  data: Prisma.XOR<Prisma.ReportDownloadCreateInput, Prisma.ReportDownloadUncheckedCreateInput>
}

/**
 * ReportDownload createMany
 */
export type ReportDownloadCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ReportDownloads.
   */
  data: Prisma.ReportDownloadCreateManyInput | Prisma.ReportDownloadCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ReportDownload update
 */
export type ReportDownloadUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportDownload
   */
  select?: Prisma.ReportDownloadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportDownload
   */
  omit?: Prisma.ReportDownloadOmit<ExtArgs> | null
  /**
   * The data needed to update a ReportDownload.
   */
  data: Prisma.XOR<Prisma.ReportDownloadUpdateInput, Prisma.ReportDownloadUncheckedUpdateInput>
  /**
   * Choose, which ReportDownload to update.
   */
  where: Prisma.ReportDownloadWhereUniqueInput
}

/**
 * ReportDownload updateMany
 */
export type ReportDownloadUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ReportDownloads.
   */
  data: Prisma.XOR<Prisma.ReportDownloadUpdateManyMutationInput, Prisma.ReportDownloadUncheckedUpdateManyInput>
  /**
   * Filter which ReportDownloads to update
   */
  where?: Prisma.ReportDownloadWhereInput
  /**
   * Limit how many ReportDownloads to update.
   */
  limit?: number
}

/**
 * ReportDownload upsert
 */
export type ReportDownloadUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportDownload
   */
  select?: Prisma.ReportDownloadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportDownload
   */
  omit?: Prisma.ReportDownloadOmit<ExtArgs> | null
  /**
   * The filter to search for the ReportDownload to update in case it exists.
   */
  where: Prisma.ReportDownloadWhereUniqueInput
  /**
   * In case the ReportDownload found by the `where` argument doesn't exist, create a new ReportDownload with this data.
   */
  create: Prisma.XOR<Prisma.ReportDownloadCreateInput, Prisma.ReportDownloadUncheckedCreateInput>
  /**
   * In case the ReportDownload was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ReportDownloadUpdateInput, Prisma.ReportDownloadUncheckedUpdateInput>
}

/**
 * ReportDownload delete
 */
export type ReportDownloadDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportDownload
   */
  select?: Prisma.ReportDownloadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportDownload
   */
  omit?: Prisma.ReportDownloadOmit<ExtArgs> | null
  /**
   * Filter which ReportDownload to delete.
   */
  where: Prisma.ReportDownloadWhereUniqueInput
}

/**
 * ReportDownload deleteMany
 */
export type ReportDownloadDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReportDownloads to delete
   */
  where?: Prisma.ReportDownloadWhereInput
  /**
   * Limit how many ReportDownloads to delete.
   */
  limit?: number
}

/**
 * ReportDownload without action
 */
export type ReportDownloadDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportDownload
   */
  select?: Prisma.ReportDownloadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportDownload
   */
  omit?: Prisma.ReportDownloadOmit<ExtArgs> | null
}
