
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ReportQueue` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ReportQueue
 * 
 */
export type ReportQueueModel = runtime.Types.Result.DefaultSelection<Prisma.$ReportQueuePayload>

export type AggregateReportQueue = {
  _count: ReportQueueCountAggregateOutputType | null
  _avg: ReportQueueAvgAggregateOutputType | null
  _sum: ReportQueueSumAggregateOutputType | null
  _min: ReportQueueMinAggregateOutputType | null
  _max: ReportQueueMaxAggregateOutputType | null
}

export type ReportQueueAvgAggregateOutputType = {
  id: number | null
}

export type ReportQueueSumAggregateOutputType = {
  id: number | null
}

export type ReportQueueMinAggregateOutputType = {
  id: number | null
  kenyaEmrReportUuid: string | null
  reportPeriod: string | null
  status: string | null
  error: string | null
  createdAt: Date | null
  processedAt: Date | null
}

export type ReportQueueMaxAggregateOutputType = {
  id: number | null
  kenyaEmrReportUuid: string | null
  reportPeriod: string | null
  status: string | null
  error: string | null
  createdAt: Date | null
  processedAt: Date | null
}

export type ReportQueueCountAggregateOutputType = {
  id: number
  kenyaEmrReportUuid: number
  reportPeriod: number
  status: number
  error: number
  createdAt: number
  processedAt: number
  _all: number
}


export type ReportQueueAvgAggregateInputType = {
  id?: true
}

export type ReportQueueSumAggregateInputType = {
  id?: true
}

export type ReportQueueMinAggregateInputType = {
  id?: true
  kenyaEmrReportUuid?: true
  reportPeriod?: true
  status?: true
  error?: true
  createdAt?: true
  processedAt?: true
}

export type ReportQueueMaxAggregateInputType = {
  id?: true
  kenyaEmrReportUuid?: true
  reportPeriod?: true
  status?: true
  error?: true
  createdAt?: true
  processedAt?: true
}

export type ReportQueueCountAggregateInputType = {
  id?: true
  kenyaEmrReportUuid?: true
  reportPeriod?: true
  status?: true
  error?: true
  createdAt?: true
  processedAt?: true
  _all?: true
}

export type ReportQueueAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReportQueue to aggregate.
   */
  where?: Prisma.ReportQueueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReportQueues to fetch.
   */
  orderBy?: Prisma.ReportQueueOrderByWithRelationInput | Prisma.ReportQueueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ReportQueueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReportQueues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReportQueues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ReportQueues
  **/
  _count?: true | ReportQueueCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ReportQueueAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ReportQueueSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ReportQueueMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ReportQueueMaxAggregateInputType
}

export type GetReportQueueAggregateType<T extends ReportQueueAggregateArgs> = {
      [P in keyof T & keyof AggregateReportQueue]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateReportQueue[P]>
    : Prisma.GetScalarType<T[P], AggregateReportQueue[P]>
}




export type ReportQueueGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ReportQueueWhereInput
  orderBy?: Prisma.ReportQueueOrderByWithAggregationInput | Prisma.ReportQueueOrderByWithAggregationInput[]
  by: Prisma.ReportQueueScalarFieldEnum[] | Prisma.ReportQueueScalarFieldEnum
  having?: Prisma.ReportQueueScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ReportQueueCountAggregateInputType | true
  _avg?: ReportQueueAvgAggregateInputType
  _sum?: ReportQueueSumAggregateInputType
  _min?: ReportQueueMinAggregateInputType
  _max?: ReportQueueMaxAggregateInputType
}

export type ReportQueueGroupByOutputType = {
  id: number
  kenyaEmrReportUuid: string
  reportPeriod: string
  status: string
  error: string | null
  createdAt: Date
  processedAt: Date | null
  _count: ReportQueueCountAggregateOutputType | null
  _avg: ReportQueueAvgAggregateOutputType | null
  _sum: ReportQueueSumAggregateOutputType | null
  _min: ReportQueueMinAggregateOutputType | null
  _max: ReportQueueMaxAggregateOutputType | null
}

type GetReportQueueGroupByPayload<T extends ReportQueueGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ReportQueueGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ReportQueueGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ReportQueueGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ReportQueueGroupByOutputType[P]>
      }
    >
  >



export type ReportQueueWhereInput = {
  AND?: Prisma.ReportQueueWhereInput | Prisma.ReportQueueWhereInput[]
  OR?: Prisma.ReportQueueWhereInput[]
  NOT?: Prisma.ReportQueueWhereInput | Prisma.ReportQueueWhereInput[]
  id?: Prisma.IntFilter<"ReportQueue"> | number
  kenyaEmrReportUuid?: Prisma.StringFilter<"ReportQueue"> | string
  reportPeriod?: Prisma.StringFilter<"ReportQueue"> | string
  status?: Prisma.StringFilter<"ReportQueue"> | string
  error?: Prisma.StringNullableFilter<"ReportQueue"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ReportQueue"> | Date | string
  processedAt?: Prisma.DateTimeNullableFilter<"ReportQueue"> | Date | string | null
}

export type ReportQueueOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  kenyaEmrReportUuid?: Prisma.SortOrder
  reportPeriod?: Prisma.SortOrder
  status?: Prisma.SortOrder
  error?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  processedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _relevance?: Prisma.ReportQueueOrderByRelevanceInput
}

export type ReportQueueWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ReportQueueWhereInput | Prisma.ReportQueueWhereInput[]
  OR?: Prisma.ReportQueueWhereInput[]
  NOT?: Prisma.ReportQueueWhereInput | Prisma.ReportQueueWhereInput[]
  kenyaEmrReportUuid?: Prisma.StringFilter<"ReportQueue"> | string
  reportPeriod?: Prisma.StringFilter<"ReportQueue"> | string
  status?: Prisma.StringFilter<"ReportQueue"> | string
  error?: Prisma.StringNullableFilter<"ReportQueue"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ReportQueue"> | Date | string
  processedAt?: Prisma.DateTimeNullableFilter<"ReportQueue"> | Date | string | null
}, "id">

export type ReportQueueOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  kenyaEmrReportUuid?: Prisma.SortOrder
  reportPeriod?: Prisma.SortOrder
  status?: Prisma.SortOrder
  error?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  processedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ReportQueueCountOrderByAggregateInput
  _avg?: Prisma.ReportQueueAvgOrderByAggregateInput
  _max?: Prisma.ReportQueueMaxOrderByAggregateInput
  _min?: Prisma.ReportQueueMinOrderByAggregateInput
  _sum?: Prisma.ReportQueueSumOrderByAggregateInput
}

export type ReportQueueScalarWhereWithAggregatesInput = {
  AND?: Prisma.ReportQueueScalarWhereWithAggregatesInput | Prisma.ReportQueueScalarWhereWithAggregatesInput[]
  OR?: Prisma.ReportQueueScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ReportQueueScalarWhereWithAggregatesInput | Prisma.ReportQueueScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ReportQueue"> | number
  kenyaEmrReportUuid?: Prisma.StringWithAggregatesFilter<"ReportQueue"> | string
  reportPeriod?: Prisma.StringWithAggregatesFilter<"ReportQueue"> | string
  status?: Prisma.StringWithAggregatesFilter<"ReportQueue"> | string
  error?: Prisma.StringNullableWithAggregatesFilter<"ReportQueue"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ReportQueue"> | Date | string
  processedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"ReportQueue"> | Date | string | null
}

export type ReportQueueCreateInput = {
  kenyaEmrReportUuid: string
  reportPeriod: string
  status?: string
  error?: string | null
  createdAt?: Date | string
  processedAt?: Date | string | null
}

export type ReportQueueUncheckedCreateInput = {
  id?: number
  kenyaEmrReportUuid: string
  reportPeriod: string
  status?: string
  error?: string | null
  createdAt?: Date | string
  processedAt?: Date | string | null
}

export type ReportQueueUpdateInput = {
  kenyaEmrReportUuid?: Prisma.StringFieldUpdateOperationsInput | string
  reportPeriod?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ReportQueueUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  kenyaEmrReportUuid?: Prisma.StringFieldUpdateOperationsInput | string
  reportPeriod?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ReportQueueCreateManyInput = {
  id?: number
  kenyaEmrReportUuid: string
  reportPeriod: string
  status?: string
  error?: string | null
  createdAt?: Date | string
  processedAt?: Date | string | null
}

export type ReportQueueUpdateManyMutationInput = {
  kenyaEmrReportUuid?: Prisma.StringFieldUpdateOperationsInput | string
  reportPeriod?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ReportQueueUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  kenyaEmrReportUuid?: Prisma.StringFieldUpdateOperationsInput | string
  reportPeriod?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  processedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ReportQueueOrderByRelevanceInput = {
  fields: Prisma.ReportQueueOrderByRelevanceFieldEnum | Prisma.ReportQueueOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ReportQueueCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  kenyaEmrReportUuid?: Prisma.SortOrder
  reportPeriod?: Prisma.SortOrder
  status?: Prisma.SortOrder
  error?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  processedAt?: Prisma.SortOrder
}

export type ReportQueueAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type ReportQueueMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  kenyaEmrReportUuid?: Prisma.SortOrder
  reportPeriod?: Prisma.SortOrder
  status?: Prisma.SortOrder
  error?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  processedAt?: Prisma.SortOrder
}

export type ReportQueueMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  kenyaEmrReportUuid?: Prisma.SortOrder
  reportPeriod?: Prisma.SortOrder
  status?: Prisma.SortOrder
  error?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  processedAt?: Prisma.SortOrder
}

export type ReportQueueSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type ReportQueueSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  kenyaEmrReportUuid?: boolean
  reportPeriod?: boolean
  status?: boolean
  error?: boolean
  createdAt?: boolean
  processedAt?: boolean
}, ExtArgs["result"]["reportQueue"]>



export type ReportQueueSelectScalar = {
  id?: boolean
  kenyaEmrReportUuid?: boolean
  reportPeriod?: boolean
  status?: boolean
  error?: boolean
  createdAt?: boolean
  processedAt?: boolean
}

export type ReportQueueOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "kenyaEmrReportUuid" | "reportPeriod" | "status" | "error" | "createdAt" | "processedAt", ExtArgs["result"]["reportQueue"]>

export type $ReportQueuePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ReportQueue"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    kenyaEmrReportUuid: string
    reportPeriod: string
    status: string
    error: string | null
    createdAt: Date
    processedAt: Date | null
  }, ExtArgs["result"]["reportQueue"]>
  composites: {}
}

export type ReportQueueGetPayload<S extends boolean | null | undefined | ReportQueueDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ReportQueuePayload, S>

export type ReportQueueCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ReportQueueFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ReportQueueCountAggregateInputType | true
  }

export interface ReportQueueDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ReportQueue'], meta: { name: 'ReportQueue' } }
  /**
   * Find zero or one ReportQueue that matches the filter.
   * @param {ReportQueueFindUniqueArgs} args - Arguments to find a ReportQueue
   * @example
   * // Get one ReportQueue
   * const reportQueue = await prisma.reportQueue.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ReportQueueFindUniqueArgs>(args: Prisma.SelectSubset<T, ReportQueueFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ReportQueueClient<runtime.Types.Result.GetResult<Prisma.$ReportQueuePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ReportQueue that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ReportQueueFindUniqueOrThrowArgs} args - Arguments to find a ReportQueue
   * @example
   * // Get one ReportQueue
   * const reportQueue = await prisma.reportQueue.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ReportQueueFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ReportQueueFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReportQueueClient<runtime.Types.Result.GetResult<Prisma.$ReportQueuePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReportQueue that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReportQueueFindFirstArgs} args - Arguments to find a ReportQueue
   * @example
   * // Get one ReportQueue
   * const reportQueue = await prisma.reportQueue.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ReportQueueFindFirstArgs>(args?: Prisma.SelectSubset<T, ReportQueueFindFirstArgs<ExtArgs>>): Prisma.Prisma__ReportQueueClient<runtime.Types.Result.GetResult<Prisma.$ReportQueuePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ReportQueue that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReportQueueFindFirstOrThrowArgs} args - Arguments to find a ReportQueue
   * @example
   * // Get one ReportQueue
   * const reportQueue = await prisma.reportQueue.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ReportQueueFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ReportQueueFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ReportQueueClient<runtime.Types.Result.GetResult<Prisma.$ReportQueuePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ReportQueues that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReportQueueFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ReportQueues
   * const reportQueues = await prisma.reportQueue.findMany()
   * 
   * // Get first 10 ReportQueues
   * const reportQueues = await prisma.reportQueue.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const reportQueueWithIdOnly = await prisma.reportQueue.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ReportQueueFindManyArgs>(args?: Prisma.SelectSubset<T, ReportQueueFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ReportQueuePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ReportQueue.
   * @param {ReportQueueCreateArgs} args - Arguments to create a ReportQueue.
   * @example
   * // Create one ReportQueue
   * const ReportQueue = await prisma.reportQueue.create({
   *   data: {
   *     // ... data to create a ReportQueue
   *   }
   * })
   * 
   */
  create<T extends ReportQueueCreateArgs>(args: Prisma.SelectSubset<T, ReportQueueCreateArgs<ExtArgs>>): Prisma.Prisma__ReportQueueClient<runtime.Types.Result.GetResult<Prisma.$ReportQueuePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ReportQueues.
   * @param {ReportQueueCreateManyArgs} args - Arguments to create many ReportQueues.
   * @example
   * // Create many ReportQueues
   * const reportQueue = await prisma.reportQueue.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ReportQueueCreateManyArgs>(args?: Prisma.SelectSubset<T, ReportQueueCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a ReportQueue.
   * @param {ReportQueueDeleteArgs} args - Arguments to delete one ReportQueue.
   * @example
   * // Delete one ReportQueue
   * const ReportQueue = await prisma.reportQueue.delete({
   *   where: {
   *     // ... filter to delete one ReportQueue
   *   }
   * })
   * 
   */
  delete<T extends ReportQueueDeleteArgs>(args: Prisma.SelectSubset<T, ReportQueueDeleteArgs<ExtArgs>>): Prisma.Prisma__ReportQueueClient<runtime.Types.Result.GetResult<Prisma.$ReportQueuePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ReportQueue.
   * @param {ReportQueueUpdateArgs} args - Arguments to update one ReportQueue.
   * @example
   * // Update one ReportQueue
   * const reportQueue = await prisma.reportQueue.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ReportQueueUpdateArgs>(args: Prisma.SelectSubset<T, ReportQueueUpdateArgs<ExtArgs>>): Prisma.Prisma__ReportQueueClient<runtime.Types.Result.GetResult<Prisma.$ReportQueuePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ReportQueues.
   * @param {ReportQueueDeleteManyArgs} args - Arguments to filter ReportQueues to delete.
   * @example
   * // Delete a few ReportQueues
   * const { count } = await prisma.reportQueue.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ReportQueueDeleteManyArgs>(args?: Prisma.SelectSubset<T, ReportQueueDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ReportQueues.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReportQueueUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ReportQueues
   * const reportQueue = await prisma.reportQueue.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ReportQueueUpdateManyArgs>(args: Prisma.SelectSubset<T, ReportQueueUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one ReportQueue.
   * @param {ReportQueueUpsertArgs} args - Arguments to update or create a ReportQueue.
   * @example
   * // Update or create a ReportQueue
   * const reportQueue = await prisma.reportQueue.upsert({
   *   create: {
   *     // ... data to create a ReportQueue
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ReportQueue we want to update
   *   }
   * })
   */
  upsert<T extends ReportQueueUpsertArgs>(args: Prisma.SelectSubset<T, ReportQueueUpsertArgs<ExtArgs>>): Prisma.Prisma__ReportQueueClient<runtime.Types.Result.GetResult<Prisma.$ReportQueuePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ReportQueues.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReportQueueCountArgs} args - Arguments to filter ReportQueues to count.
   * @example
   * // Count the number of ReportQueues
   * const count = await prisma.reportQueue.count({
   *   where: {
   *     // ... the filter for the ReportQueues we want to count
   *   }
   * })
  **/
  count<T extends ReportQueueCountArgs>(
    args?: Prisma.Subset<T, ReportQueueCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ReportQueueCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ReportQueue.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReportQueueAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ReportQueueAggregateArgs>(args: Prisma.Subset<T, ReportQueueAggregateArgs>): Prisma.PrismaPromise<GetReportQueueAggregateType<T>>

  /**
   * Group by ReportQueue.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ReportQueueGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ReportQueueGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ReportQueueGroupByArgs['orderBy'] }
      : { orderBy?: ReportQueueGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ReportQueueGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetReportQueueGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ReportQueue model
 */
readonly fields: ReportQueueFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ReportQueue.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ReportQueueClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ReportQueue model
 */
export interface ReportQueueFieldRefs {
  readonly id: Prisma.FieldRef<"ReportQueue", 'Int'>
  readonly kenyaEmrReportUuid: Prisma.FieldRef<"ReportQueue", 'String'>
  readonly reportPeriod: Prisma.FieldRef<"ReportQueue", 'String'>
  readonly status: Prisma.FieldRef<"ReportQueue", 'String'>
  readonly error: Prisma.FieldRef<"ReportQueue", 'String'>
  readonly createdAt: Prisma.FieldRef<"ReportQueue", 'DateTime'>
  readonly processedAt: Prisma.FieldRef<"ReportQueue", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ReportQueue findUnique
 */
export type ReportQueueFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportQueue
   */
  select?: Prisma.ReportQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportQueue
   */
  omit?: Prisma.ReportQueueOmit<ExtArgs> | null
  /**
   * Filter, which ReportQueue to fetch.
   */
  where: Prisma.ReportQueueWhereUniqueInput
}

/**
 * ReportQueue findUniqueOrThrow
 */
export type ReportQueueFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportQueue
   */
  select?: Prisma.ReportQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportQueue
   */
  omit?: Prisma.ReportQueueOmit<ExtArgs> | null
  /**
   * Filter, which ReportQueue to fetch.
   */
  where: Prisma.ReportQueueWhereUniqueInput
}

/**
 * ReportQueue findFirst
 */
export type ReportQueueFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportQueue
   */
  select?: Prisma.ReportQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportQueue
   */
  omit?: Prisma.ReportQueueOmit<ExtArgs> | null
  /**
   * Filter, which ReportQueue to fetch.
   */
  where?: Prisma.ReportQueueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReportQueues to fetch.
   */
  orderBy?: Prisma.ReportQueueOrderByWithRelationInput | Prisma.ReportQueueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReportQueues.
   */
  cursor?: Prisma.ReportQueueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReportQueues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReportQueues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReportQueues.
   */
  distinct?: Prisma.ReportQueueScalarFieldEnum | Prisma.ReportQueueScalarFieldEnum[]
}

/**
 * ReportQueue findFirstOrThrow
 */
export type ReportQueueFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportQueue
   */
  select?: Prisma.ReportQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportQueue
   */
  omit?: Prisma.ReportQueueOmit<ExtArgs> | null
  /**
   * Filter, which ReportQueue to fetch.
   */
  where?: Prisma.ReportQueueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReportQueues to fetch.
   */
  orderBy?: Prisma.ReportQueueOrderByWithRelationInput | Prisma.ReportQueueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ReportQueues.
   */
  cursor?: Prisma.ReportQueueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReportQueues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReportQueues.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ReportQueues.
   */
  distinct?: Prisma.ReportQueueScalarFieldEnum | Prisma.ReportQueueScalarFieldEnum[]
}

/**
 * ReportQueue findMany
 */
export type ReportQueueFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportQueue
   */
  select?: Prisma.ReportQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportQueue
   */
  omit?: Prisma.ReportQueueOmit<ExtArgs> | null
  /**
   * Filter, which ReportQueues to fetch.
   */
  where?: Prisma.ReportQueueWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ReportQueues to fetch.
   */
  orderBy?: Prisma.ReportQueueOrderByWithRelationInput | Prisma.ReportQueueOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ReportQueues.
   */
  cursor?: Prisma.ReportQueueWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ReportQueues from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ReportQueues.
   */
  skip?: number
  distinct?: Prisma.ReportQueueScalarFieldEnum | Prisma.ReportQueueScalarFieldEnum[]
}

/**
 * ReportQueue create
 */
export type ReportQueueCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportQueue
   */
  select?: Prisma.ReportQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportQueue
   */
  omit?: Prisma.ReportQueueOmit<ExtArgs> | null
  /**
   * The data needed to create a ReportQueue.
   */
  data: Prisma.XOR<Prisma.ReportQueueCreateInput, Prisma.ReportQueueUncheckedCreateInput>
}

/**
 * ReportQueue createMany
 */
export type ReportQueueCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ReportQueues.
   */
  data: Prisma.ReportQueueCreateManyInput | Prisma.ReportQueueCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ReportQueue update
 */
export type ReportQueueUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportQueue
   */
  select?: Prisma.ReportQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportQueue
   */
  omit?: Prisma.ReportQueueOmit<ExtArgs> | null
  /**
   * The data needed to update a ReportQueue.
   */
  data: Prisma.XOR<Prisma.ReportQueueUpdateInput, Prisma.ReportQueueUncheckedUpdateInput>
  /**
   * Choose, which ReportQueue to update.
   */
  where: Prisma.ReportQueueWhereUniqueInput
}

/**
 * ReportQueue updateMany
 */
export type ReportQueueUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ReportQueues.
   */
  data: Prisma.XOR<Prisma.ReportQueueUpdateManyMutationInput, Prisma.ReportQueueUncheckedUpdateManyInput>
  /**
   * Filter which ReportQueues to update
   */
  where?: Prisma.ReportQueueWhereInput
  /**
   * Limit how many ReportQueues to update.
   */
  limit?: number
}

/**
 * ReportQueue upsert
 */
export type ReportQueueUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportQueue
   */
  select?: Prisma.ReportQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportQueue
   */
  omit?: Prisma.ReportQueueOmit<ExtArgs> | null
  /**
   * The filter to search for the ReportQueue to update in case it exists.
   */
  where: Prisma.ReportQueueWhereUniqueInput
  /**
   * In case the ReportQueue found by the `where` argument doesn't exist, create a new ReportQueue with this data.
   */
  create: Prisma.XOR<Prisma.ReportQueueCreateInput, Prisma.ReportQueueUncheckedCreateInput>
  /**
   * In case the ReportQueue was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ReportQueueUpdateInput, Prisma.ReportQueueUncheckedUpdateInput>
}

/**
 * ReportQueue delete
 */
export type ReportQueueDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportQueue
   */
  select?: Prisma.ReportQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportQueue
   */
  omit?: Prisma.ReportQueueOmit<ExtArgs> | null
  /**
   * Filter which ReportQueue to delete.
   */
  where: Prisma.ReportQueueWhereUniqueInput
}

/**
 * ReportQueue deleteMany
 */
export type ReportQueueDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ReportQueues to delete
   */
  where?: Prisma.ReportQueueWhereInput
  /**
   * Limit how many ReportQueues to delete.
   */
  limit?: number
}

/**
 * ReportQueue without action
 */
export type ReportQueueDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ReportQueue
   */
  select?: Prisma.ReportQueueSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ReportQueue
   */
  omit?: Prisma.ReportQueueOmit<ExtArgs> | null
}
