
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `StagedIndicator` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model StagedIndicator
 * 
 */
export type StagedIndicatorModel = runtime.Types.Result.DefaultSelection<Prisma.$StagedIndicatorPayload>

export type AggregateStagedIndicator = {
  _count: StagedIndicatorCountAggregateOutputType | null
  _avg: StagedIndicatorAvgAggregateOutputType | null
  _sum: StagedIndicatorSumAggregateOutputType | null
  _min: StagedIndicatorMinAggregateOutputType | null
  _max: StagedIndicatorMaxAggregateOutputType | null
}

export type StagedIndicatorAvgAggregateOutputType = {
  id: number | null
}

export type StagedIndicatorSumAggregateOutputType = {
  id: number | null
}

export type StagedIndicatorMinAggregateOutputType = {
  id: number | null
  indicatorCode: string | null
  startDate: Date | null
  endDate: Date | null
  createdAt: Date | null
  syncedToAmpathAt: Date | null
}

export type StagedIndicatorMaxAggregateOutputType = {
  id: number | null
  indicatorCode: string | null
  startDate: Date | null
  endDate: Date | null
  createdAt: Date | null
  syncedToAmpathAt: Date | null
}

export type StagedIndicatorCountAggregateOutputType = {
  id: number
  indicatorCode: number
  rawResult: number
  startDate: number
  endDate: number
  createdAt: number
  syncedToAmpathAt: number
  _all: number
}


export type StagedIndicatorAvgAggregateInputType = {
  id?: true
}

export type StagedIndicatorSumAggregateInputType = {
  id?: true
}

export type StagedIndicatorMinAggregateInputType = {
  id?: true
  indicatorCode?: true
  startDate?: true
  endDate?: true
  createdAt?: true
  syncedToAmpathAt?: true
}

export type StagedIndicatorMaxAggregateInputType = {
  id?: true
  indicatorCode?: true
  startDate?: true
  endDate?: true
  createdAt?: true
  syncedToAmpathAt?: true
}

export type StagedIndicatorCountAggregateInputType = {
  id?: true
  indicatorCode?: true
  rawResult?: true
  startDate?: true
  endDate?: true
  createdAt?: true
  syncedToAmpathAt?: true
  _all?: true
}

export type StagedIndicatorAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StagedIndicator to aggregate.
   */
  where?: Prisma.StagedIndicatorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StagedIndicators to fetch.
   */
  orderBy?: Prisma.StagedIndicatorOrderByWithRelationInput | Prisma.StagedIndicatorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StagedIndicatorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StagedIndicators from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StagedIndicators.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned StagedIndicators
  **/
  _count?: true | StagedIndicatorCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: StagedIndicatorAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: StagedIndicatorSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StagedIndicatorMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StagedIndicatorMaxAggregateInputType
}

export type GetStagedIndicatorAggregateType<T extends StagedIndicatorAggregateArgs> = {
      [P in keyof T & keyof AggregateStagedIndicator]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStagedIndicator[P]>
    : Prisma.GetScalarType<T[P], AggregateStagedIndicator[P]>
}




export type StagedIndicatorGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StagedIndicatorWhereInput
  orderBy?: Prisma.StagedIndicatorOrderByWithAggregationInput | Prisma.StagedIndicatorOrderByWithAggregationInput[]
  by: Prisma.StagedIndicatorScalarFieldEnum[] | Prisma.StagedIndicatorScalarFieldEnum
  having?: Prisma.StagedIndicatorScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StagedIndicatorCountAggregateInputType | true
  _avg?: StagedIndicatorAvgAggregateInputType
  _sum?: StagedIndicatorSumAggregateInputType
  _min?: StagedIndicatorMinAggregateInputType
  _max?: StagedIndicatorMaxAggregateInputType
}

export type StagedIndicatorGroupByOutputType = {
  id: number
  indicatorCode: string
  rawResult: runtime.JsonValue
  startDate: Date
  endDate: Date
  createdAt: Date
  syncedToAmpathAt: Date | null
  _count: StagedIndicatorCountAggregateOutputType | null
  _avg: StagedIndicatorAvgAggregateOutputType | null
  _sum: StagedIndicatorSumAggregateOutputType | null
  _min: StagedIndicatorMinAggregateOutputType | null
  _max: StagedIndicatorMaxAggregateOutputType | null
}

type GetStagedIndicatorGroupByPayload<T extends StagedIndicatorGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StagedIndicatorGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StagedIndicatorGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StagedIndicatorGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StagedIndicatorGroupByOutputType[P]>
      }
    >
  >



export type StagedIndicatorWhereInput = {
  AND?: Prisma.StagedIndicatorWhereInput | Prisma.StagedIndicatorWhereInput[]
  OR?: Prisma.StagedIndicatorWhereInput[]
  NOT?: Prisma.StagedIndicatorWhereInput | Prisma.StagedIndicatorWhereInput[]
  id?: Prisma.IntFilter<"StagedIndicator"> | number
  indicatorCode?: Prisma.StringFilter<"StagedIndicator"> | string
  rawResult?: Prisma.JsonFilter<"StagedIndicator">
  startDate?: Prisma.DateTimeFilter<"StagedIndicator"> | Date | string
  endDate?: Prisma.DateTimeFilter<"StagedIndicator"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"StagedIndicator"> | Date | string
  syncedToAmpathAt?: Prisma.DateTimeNullableFilter<"StagedIndicator"> | Date | string | null
}

export type StagedIndicatorOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  indicatorCode?: Prisma.SortOrder
  rawResult?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  syncedToAmpathAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _relevance?: Prisma.StagedIndicatorOrderByRelevanceInput
}

export type StagedIndicatorWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.StagedIndicatorWhereInput | Prisma.StagedIndicatorWhereInput[]
  OR?: Prisma.StagedIndicatorWhereInput[]
  NOT?: Prisma.StagedIndicatorWhereInput | Prisma.StagedIndicatorWhereInput[]
  indicatorCode?: Prisma.StringFilter<"StagedIndicator"> | string
  rawResult?: Prisma.JsonFilter<"StagedIndicator">
  startDate?: Prisma.DateTimeFilter<"StagedIndicator"> | Date | string
  endDate?: Prisma.DateTimeFilter<"StagedIndicator"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"StagedIndicator"> | Date | string
  syncedToAmpathAt?: Prisma.DateTimeNullableFilter<"StagedIndicator"> | Date | string | null
}, "id">

export type StagedIndicatorOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  indicatorCode?: Prisma.SortOrder
  rawResult?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  syncedToAmpathAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.StagedIndicatorCountOrderByAggregateInput
  _avg?: Prisma.StagedIndicatorAvgOrderByAggregateInput
  _max?: Prisma.StagedIndicatorMaxOrderByAggregateInput
  _min?: Prisma.StagedIndicatorMinOrderByAggregateInput
  _sum?: Prisma.StagedIndicatorSumOrderByAggregateInput
}

export type StagedIndicatorScalarWhereWithAggregatesInput = {
  AND?: Prisma.StagedIndicatorScalarWhereWithAggregatesInput | Prisma.StagedIndicatorScalarWhereWithAggregatesInput[]
  OR?: Prisma.StagedIndicatorScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StagedIndicatorScalarWhereWithAggregatesInput | Prisma.StagedIndicatorScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"StagedIndicator"> | number
  indicatorCode?: Prisma.StringWithAggregatesFilter<"StagedIndicator"> | string
  rawResult?: Prisma.JsonWithAggregatesFilter<"StagedIndicator">
  startDate?: Prisma.DateTimeWithAggregatesFilter<"StagedIndicator"> | Date | string
  endDate?: Prisma.DateTimeWithAggregatesFilter<"StagedIndicator"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"StagedIndicator"> | Date | string
  syncedToAmpathAt?: Prisma.DateTimeNullableWithAggregatesFilter<"StagedIndicator"> | Date | string | null
}

export type StagedIndicatorCreateInput = {
  indicatorCode: string
  rawResult: Prisma.JsonNullValueInput | runtime.InputJsonValue
  startDate: Date | string
  endDate: Date | string
  createdAt?: Date | string
  syncedToAmpathAt?: Date | string | null
}

export type StagedIndicatorUncheckedCreateInput = {
  id?: number
  indicatorCode: string
  rawResult: Prisma.JsonNullValueInput | runtime.InputJsonValue
  startDate: Date | string
  endDate: Date | string
  createdAt?: Date | string
  syncedToAmpathAt?: Date | string | null
}

export type StagedIndicatorUpdateInput = {
  indicatorCode?: Prisma.StringFieldUpdateOperationsInput | string
  rawResult?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedToAmpathAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type StagedIndicatorUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  indicatorCode?: Prisma.StringFieldUpdateOperationsInput | string
  rawResult?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedToAmpathAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type StagedIndicatorCreateManyInput = {
  id?: number
  indicatorCode: string
  rawResult: Prisma.JsonNullValueInput | runtime.InputJsonValue
  startDate: Date | string
  endDate: Date | string
  createdAt?: Date | string
  syncedToAmpathAt?: Date | string | null
}

export type StagedIndicatorUpdateManyMutationInput = {
  indicatorCode?: Prisma.StringFieldUpdateOperationsInput | string
  rawResult?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedToAmpathAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type StagedIndicatorUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  indicatorCode?: Prisma.StringFieldUpdateOperationsInput | string
  rawResult?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  startDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  syncedToAmpathAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type StagedIndicatorOrderByRelevanceInput = {
  fields: Prisma.StagedIndicatorOrderByRelevanceFieldEnum | Prisma.StagedIndicatorOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type StagedIndicatorCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  indicatorCode?: Prisma.SortOrder
  rawResult?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  syncedToAmpathAt?: Prisma.SortOrder
}

export type StagedIndicatorAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type StagedIndicatorMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  indicatorCode?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  syncedToAmpathAt?: Prisma.SortOrder
}

export type StagedIndicatorMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  indicatorCode?: Prisma.SortOrder
  startDate?: Prisma.SortOrder
  endDate?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  syncedToAmpathAt?: Prisma.SortOrder
}

export type StagedIndicatorSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}



export type StagedIndicatorSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  indicatorCode?: boolean
  rawResult?: boolean
  startDate?: boolean
  endDate?: boolean
  createdAt?: boolean
  syncedToAmpathAt?: boolean
}, ExtArgs["result"]["stagedIndicator"]>



export type StagedIndicatorSelectScalar = {
  id?: boolean
  indicatorCode?: boolean
  rawResult?: boolean
  startDate?: boolean
  endDate?: boolean
  createdAt?: boolean
  syncedToAmpathAt?: boolean
}

export type StagedIndicatorOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "indicatorCode" | "rawResult" | "startDate" | "endDate" | "createdAt" | "syncedToAmpathAt", ExtArgs["result"]["stagedIndicator"]>

export type $StagedIndicatorPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "StagedIndicator"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    indicatorCode: string
    rawResult: runtime.JsonValue
    startDate: Date
    endDate: Date
    createdAt: Date
    syncedToAmpathAt: Date | null
  }, ExtArgs["result"]["stagedIndicator"]>
  composites: {}
}

export type StagedIndicatorGetPayload<S extends boolean | null | undefined | StagedIndicatorDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StagedIndicatorPayload, S>

export type StagedIndicatorCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StagedIndicatorFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StagedIndicatorCountAggregateInputType | true
  }

export interface StagedIndicatorDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['StagedIndicator'], meta: { name: 'StagedIndicator' } }
  /**
   * Find zero or one StagedIndicator that matches the filter.
   * @param {StagedIndicatorFindUniqueArgs} args - Arguments to find a StagedIndicator
   * @example
   * // Get one StagedIndicator
   * const stagedIndicator = await prisma.stagedIndicator.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StagedIndicatorFindUniqueArgs>(args: Prisma.SelectSubset<T, StagedIndicatorFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StagedIndicatorClient<runtime.Types.Result.GetResult<Prisma.$StagedIndicatorPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one StagedIndicator that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StagedIndicatorFindUniqueOrThrowArgs} args - Arguments to find a StagedIndicator
   * @example
   * // Get one StagedIndicator
   * const stagedIndicator = await prisma.stagedIndicator.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StagedIndicatorFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StagedIndicatorFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StagedIndicatorClient<runtime.Types.Result.GetResult<Prisma.$StagedIndicatorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StagedIndicator that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StagedIndicatorFindFirstArgs} args - Arguments to find a StagedIndicator
   * @example
   * // Get one StagedIndicator
   * const stagedIndicator = await prisma.stagedIndicator.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StagedIndicatorFindFirstArgs>(args?: Prisma.SelectSubset<T, StagedIndicatorFindFirstArgs<ExtArgs>>): Prisma.Prisma__StagedIndicatorClient<runtime.Types.Result.GetResult<Prisma.$StagedIndicatorPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StagedIndicator that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StagedIndicatorFindFirstOrThrowArgs} args - Arguments to find a StagedIndicator
   * @example
   * // Get one StagedIndicator
   * const stagedIndicator = await prisma.stagedIndicator.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StagedIndicatorFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StagedIndicatorFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StagedIndicatorClient<runtime.Types.Result.GetResult<Prisma.$StagedIndicatorPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more StagedIndicators that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StagedIndicatorFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all StagedIndicators
   * const stagedIndicators = await prisma.stagedIndicator.findMany()
   * 
   * // Get first 10 StagedIndicators
   * const stagedIndicators = await prisma.stagedIndicator.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const stagedIndicatorWithIdOnly = await prisma.stagedIndicator.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StagedIndicatorFindManyArgs>(args?: Prisma.SelectSubset<T, StagedIndicatorFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StagedIndicatorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a StagedIndicator.
   * @param {StagedIndicatorCreateArgs} args - Arguments to create a StagedIndicator.
   * @example
   * // Create one StagedIndicator
   * const StagedIndicator = await prisma.stagedIndicator.create({
   *   data: {
   *     // ... data to create a StagedIndicator
   *   }
   * })
   * 
   */
  create<T extends StagedIndicatorCreateArgs>(args: Prisma.SelectSubset<T, StagedIndicatorCreateArgs<ExtArgs>>): Prisma.Prisma__StagedIndicatorClient<runtime.Types.Result.GetResult<Prisma.$StagedIndicatorPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many StagedIndicators.
   * @param {StagedIndicatorCreateManyArgs} args - Arguments to create many StagedIndicators.
   * @example
   * // Create many StagedIndicators
   * const stagedIndicator = await prisma.stagedIndicator.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StagedIndicatorCreateManyArgs>(args?: Prisma.SelectSubset<T, StagedIndicatorCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a StagedIndicator.
   * @param {StagedIndicatorDeleteArgs} args - Arguments to delete one StagedIndicator.
   * @example
   * // Delete one StagedIndicator
   * const StagedIndicator = await prisma.stagedIndicator.delete({
   *   where: {
   *     // ... filter to delete one StagedIndicator
   *   }
   * })
   * 
   */
  delete<T extends StagedIndicatorDeleteArgs>(args: Prisma.SelectSubset<T, StagedIndicatorDeleteArgs<ExtArgs>>): Prisma.Prisma__StagedIndicatorClient<runtime.Types.Result.GetResult<Prisma.$StagedIndicatorPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one StagedIndicator.
   * @param {StagedIndicatorUpdateArgs} args - Arguments to update one StagedIndicator.
   * @example
   * // Update one StagedIndicator
   * const stagedIndicator = await prisma.stagedIndicator.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StagedIndicatorUpdateArgs>(args: Prisma.SelectSubset<T, StagedIndicatorUpdateArgs<ExtArgs>>): Prisma.Prisma__StagedIndicatorClient<runtime.Types.Result.GetResult<Prisma.$StagedIndicatorPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more StagedIndicators.
   * @param {StagedIndicatorDeleteManyArgs} args - Arguments to filter StagedIndicators to delete.
   * @example
   * // Delete a few StagedIndicators
   * const { count } = await prisma.stagedIndicator.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StagedIndicatorDeleteManyArgs>(args?: Prisma.SelectSubset<T, StagedIndicatorDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StagedIndicators.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StagedIndicatorUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many StagedIndicators
   * const stagedIndicator = await prisma.stagedIndicator.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StagedIndicatorUpdateManyArgs>(args: Prisma.SelectSubset<T, StagedIndicatorUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one StagedIndicator.
   * @param {StagedIndicatorUpsertArgs} args - Arguments to update or create a StagedIndicator.
   * @example
   * // Update or create a StagedIndicator
   * const stagedIndicator = await prisma.stagedIndicator.upsert({
   *   create: {
   *     // ... data to create a StagedIndicator
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the StagedIndicator we want to update
   *   }
   * })
   */
  upsert<T extends StagedIndicatorUpsertArgs>(args: Prisma.SelectSubset<T, StagedIndicatorUpsertArgs<ExtArgs>>): Prisma.Prisma__StagedIndicatorClient<runtime.Types.Result.GetResult<Prisma.$StagedIndicatorPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of StagedIndicators.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StagedIndicatorCountArgs} args - Arguments to filter StagedIndicators to count.
   * @example
   * // Count the number of StagedIndicators
   * const count = await prisma.stagedIndicator.count({
   *   where: {
   *     // ... the filter for the StagedIndicators we want to count
   *   }
   * })
  **/
  count<T extends StagedIndicatorCountArgs>(
    args?: Prisma.Subset<T, StagedIndicatorCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StagedIndicatorCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a StagedIndicator.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StagedIndicatorAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StagedIndicatorAggregateArgs>(args: Prisma.Subset<T, StagedIndicatorAggregateArgs>): Prisma.PrismaPromise<GetStagedIndicatorAggregateType<T>>

  /**
   * Group by StagedIndicator.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StagedIndicatorGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StagedIndicatorGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StagedIndicatorGroupByArgs['orderBy'] }
      : { orderBy?: StagedIndicatorGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StagedIndicatorGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStagedIndicatorGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the StagedIndicator model
 */
readonly fields: StagedIndicatorFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for StagedIndicator.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StagedIndicatorClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the StagedIndicator model
 */
export interface StagedIndicatorFieldRefs {
  readonly id: Prisma.FieldRef<"StagedIndicator", 'Int'>
  readonly indicatorCode: Prisma.FieldRef<"StagedIndicator", 'String'>
  readonly rawResult: Prisma.FieldRef<"StagedIndicator", 'Json'>
  readonly startDate: Prisma.FieldRef<"StagedIndicator", 'DateTime'>
  readonly endDate: Prisma.FieldRef<"StagedIndicator", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"StagedIndicator", 'DateTime'>
  readonly syncedToAmpathAt: Prisma.FieldRef<"StagedIndicator", 'DateTime'>
}
    

// Custom InputTypes
/**
 * StagedIndicator findUnique
 */
export type StagedIndicatorFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StagedIndicator
   */
  select?: Prisma.StagedIndicatorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StagedIndicator
   */
  omit?: Prisma.StagedIndicatorOmit<ExtArgs> | null
  /**
   * Filter, which StagedIndicator to fetch.
   */
  where: Prisma.StagedIndicatorWhereUniqueInput
}

/**
 * StagedIndicator findUniqueOrThrow
 */
export type StagedIndicatorFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StagedIndicator
   */
  select?: Prisma.StagedIndicatorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StagedIndicator
   */
  omit?: Prisma.StagedIndicatorOmit<ExtArgs> | null
  /**
   * Filter, which StagedIndicator to fetch.
   */
  where: Prisma.StagedIndicatorWhereUniqueInput
}

/**
 * StagedIndicator findFirst
 */
export type StagedIndicatorFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StagedIndicator
   */
  select?: Prisma.StagedIndicatorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StagedIndicator
   */
  omit?: Prisma.StagedIndicatorOmit<ExtArgs> | null
  /**
   * Filter, which StagedIndicator to fetch.
   */
  where?: Prisma.StagedIndicatorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StagedIndicators to fetch.
   */
  orderBy?: Prisma.StagedIndicatorOrderByWithRelationInput | Prisma.StagedIndicatorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StagedIndicators.
   */
  cursor?: Prisma.StagedIndicatorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StagedIndicators from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StagedIndicators.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StagedIndicators.
   */
  distinct?: Prisma.StagedIndicatorScalarFieldEnum | Prisma.StagedIndicatorScalarFieldEnum[]
}

/**
 * StagedIndicator findFirstOrThrow
 */
export type StagedIndicatorFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StagedIndicator
   */
  select?: Prisma.StagedIndicatorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StagedIndicator
   */
  omit?: Prisma.StagedIndicatorOmit<ExtArgs> | null
  /**
   * Filter, which StagedIndicator to fetch.
   */
  where?: Prisma.StagedIndicatorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StagedIndicators to fetch.
   */
  orderBy?: Prisma.StagedIndicatorOrderByWithRelationInput | Prisma.StagedIndicatorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StagedIndicators.
   */
  cursor?: Prisma.StagedIndicatorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StagedIndicators from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StagedIndicators.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StagedIndicators.
   */
  distinct?: Prisma.StagedIndicatorScalarFieldEnum | Prisma.StagedIndicatorScalarFieldEnum[]
}

/**
 * StagedIndicator findMany
 */
export type StagedIndicatorFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StagedIndicator
   */
  select?: Prisma.StagedIndicatorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StagedIndicator
   */
  omit?: Prisma.StagedIndicatorOmit<ExtArgs> | null
  /**
   * Filter, which StagedIndicators to fetch.
   */
  where?: Prisma.StagedIndicatorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StagedIndicators to fetch.
   */
  orderBy?: Prisma.StagedIndicatorOrderByWithRelationInput | Prisma.StagedIndicatorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing StagedIndicators.
   */
  cursor?: Prisma.StagedIndicatorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StagedIndicators from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StagedIndicators.
   */
  skip?: number
  distinct?: Prisma.StagedIndicatorScalarFieldEnum | Prisma.StagedIndicatorScalarFieldEnum[]
}

/**
 * StagedIndicator create
 */
export type StagedIndicatorCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StagedIndicator
   */
  select?: Prisma.StagedIndicatorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StagedIndicator
   */
  omit?: Prisma.StagedIndicatorOmit<ExtArgs> | null
  /**
   * The data needed to create a StagedIndicator.
   */
  data: Prisma.XOR<Prisma.StagedIndicatorCreateInput, Prisma.StagedIndicatorUncheckedCreateInput>
}

/**
 * StagedIndicator createMany
 */
export type StagedIndicatorCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many StagedIndicators.
   */
  data: Prisma.StagedIndicatorCreateManyInput | Prisma.StagedIndicatorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * StagedIndicator update
 */
export type StagedIndicatorUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StagedIndicator
   */
  select?: Prisma.StagedIndicatorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StagedIndicator
   */
  omit?: Prisma.StagedIndicatorOmit<ExtArgs> | null
  /**
   * The data needed to update a StagedIndicator.
   */
  data: Prisma.XOR<Prisma.StagedIndicatorUpdateInput, Prisma.StagedIndicatorUncheckedUpdateInput>
  /**
   * Choose, which StagedIndicator to update.
   */
  where: Prisma.StagedIndicatorWhereUniqueInput
}

/**
 * StagedIndicator updateMany
 */
export type StagedIndicatorUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update StagedIndicators.
   */
  data: Prisma.XOR<Prisma.StagedIndicatorUpdateManyMutationInput, Prisma.StagedIndicatorUncheckedUpdateManyInput>
  /**
   * Filter which StagedIndicators to update
   */
  where?: Prisma.StagedIndicatorWhereInput
  /**
   * Limit how many StagedIndicators to update.
   */
  limit?: number
}

/**
 * StagedIndicator upsert
 */
export type StagedIndicatorUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StagedIndicator
   */
  select?: Prisma.StagedIndicatorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StagedIndicator
   */
  omit?: Prisma.StagedIndicatorOmit<ExtArgs> | null
  /**
   * The filter to search for the StagedIndicator to update in case it exists.
   */
  where: Prisma.StagedIndicatorWhereUniqueInput
  /**
   * In case the StagedIndicator found by the `where` argument doesn't exist, create a new StagedIndicator with this data.
   */
  create: Prisma.XOR<Prisma.StagedIndicatorCreateInput, Prisma.StagedIndicatorUncheckedCreateInput>
  /**
   * In case the StagedIndicator was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StagedIndicatorUpdateInput, Prisma.StagedIndicatorUncheckedUpdateInput>
}

/**
 * StagedIndicator delete
 */
export type StagedIndicatorDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StagedIndicator
   */
  select?: Prisma.StagedIndicatorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StagedIndicator
   */
  omit?: Prisma.StagedIndicatorOmit<ExtArgs> | null
  /**
   * Filter which StagedIndicator to delete.
   */
  where: Prisma.StagedIndicatorWhereUniqueInput
}

/**
 * StagedIndicator deleteMany
 */
export type StagedIndicatorDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StagedIndicators to delete
   */
  where?: Prisma.StagedIndicatorWhereInput
  /**
   * Limit how many StagedIndicators to delete.
   */
  limit?: number
}

/**
 * StagedIndicator without action
 */
export type StagedIndicatorDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StagedIndicator
   */
  select?: Prisma.StagedIndicatorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StagedIndicator
   */
  omit?: Prisma.StagedIndicatorOmit<ExtArgs> | null
}
